import DashboardLayout from "@/components/DashboardLayout";
import { DevelopmentPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DEVELOPMENT_PANDALS } from "@shared/pujaData";
import { Archive, CheckCircle2, FileUp, MapPinned, Plus, Upload } from "lucide-react";
import { toast } from "sonner";

export default function Admin() {
  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-7 p-2 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-5"><div><DevelopmentPill /><p className="eyebrow mt-5">Administration</p><h1 className="font-display mt-1 text-4xl font-bold text-[#45221e]">Seasonal data control room</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-[#765e53]">The database schema, verification metadata, import boundaries, and seasons are in place. This protected workspace is the foundation for verified data operations.</p></div><Button onClick={() => toast.message("Pandal creation form is the next protected workflow.")} className="rounded-xl bg-[#8c1e21] hover:bg-[#671214]"><Plus size={16} />Add pandal</Button></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-[#fffaf0] p-5 ring-1 ring-[#e8d8c0]"><CheckCircle2 className="text-[#3e766b]" /><strong className="font-display mt-4 block text-2xl text-[#4a2520]">0</strong><span className="text-xs text-[#80675a]">verified 2026 records</span></div><div className="rounded-2xl bg-[#fffaf0] p-5 ring-1 ring-[#e8d8c0]"><MapPinned className="text-[#a22223]" /><strong className="font-display mt-4 block text-2xl text-[#4a2520]">{DEVELOPMENT_PANDALS.length}</strong><span className="text-xs text-[#80675a]">development records</span></div><div className="rounded-2xl bg-[#fffaf0] p-5 ring-1 ring-[#e8d8c0]"><Archive className="text-[#a36e28]" /><strong className="font-display mt-4 block text-2xl text-[#4a2520]">Draft</strong><span className="text-xs text-[#80675a]">2026 season status</span></div></div><section className="rounded-[1.5rem] bg-[#fffaf0] p-6 ring-1 ring-[#ead9c0]"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-2xl font-bold text-[#4a2520]">Seasonal import</h2><p className="mt-1 text-sm text-[#80675a]">Import CSV or JSON after validation; source name, source URL, verification time, and season remain attached to each record.</p></div><Button onClick={() => toast.message("Import UI will validate file columns before database writes.")} variant="outline" className="rounded-xl border-[#d5bd96] bg-[#fff9ed] text-[#7c2521]"><FileUp size={16} />Import data</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><Input placeholder="Season file path or upload binding" disabled className="h-11 border-[#e1cfb0] bg-[#f7efe1]" /><Button onClick={() => toast.message("Export is available after the first verified seasonal import.")} className="h-11 rounded-xl bg-[#413130] hover:bg-[#291b1b]"><Upload size={16} />Export backup</Button></div></section></div></DashboardLayout>;
}
