import { useEffect, useRef, useState } from "react";
import { Camera, CameraOff, Images, Loader2, RefreshCw, Save, SwitchCamera } from "lucide-react";
import { Button } from "@/components/ui/button";

type Facing = "environment" | "user";
function usePreviewUrl(blob: Blob | null) { const [url, setUrl] = useState(""); useEffect(() => { if (!blob) { setUrl(""); return; } const next = URL.createObjectURL(blob); setUrl(next); return () => URL.revokeObjectURL(next); }, [blob]); return url; }
async function compressedImage(file: Blob) {
  const url = URL.createObjectURL(file); const image = new Image();
  try { await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("IMAGE_UNREADABLE")); image.src = url; }); const scale = Math.min(1, 1600 / Math.max(image.width, image.height)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); const context = canvas.getContext("2d"); if (!context) throw new Error("CANVAS_UNAVAILABLE"); context.drawImage(image, 0, 0, canvas.width, canvas.height); return await new Promise<Blob>((resolve, reject) => canvas.toBlob(blob => blob ? resolve(blob) : reject(new Error("IMAGE_ENCODE_FAILED")), "image/jpeg", .86)); } finally { URL.revokeObjectURL(url); }
}

export function AmarPujaCamera({ onSave, bengali }: { onSave: (blob: Blob) => Promise<void>; bengali: boolean }) {
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const fileInput = useRef<HTMLInputElement>(null);
  const [facing, setFacing] = useState<Facing>("environment"); const [state, setState] = useState<"idle" | "starting" | "ready" | "unsupported" | "denied" | "error" | "saving">("idle"); const [pendingPhoto, setPendingPhoto] = useState<Blob | null>(null);
  const previewUrl = usePreviewUrl(pendingPhoto);
  const stopCamera = () => { stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; };
  useEffect(() => () => stopCamera(), []);
  const startCamera = async (nextFacing = facing) => { if (!navigator.mediaDevices?.getUserMedia) { setState("unsupported"); return; } setState("starting"); stopCamera(); try { const next = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: nextFacing }, width: { ideal: 1600 }, height: { ideal: 1200 } }, audio: false }); stream.current = next; if (video.current) { video.current.srcObject = next; await video.current.play(); } setState("ready"); } catch (error) { setState(error instanceof DOMException && error.name === "NotAllowedError" ? "denied" : "error"); } };
  const capture = async () => { if (!video.current || !video.current.videoWidth) return; const canvas = document.createElement("canvas"); canvas.width = video.current.videoWidth; canvas.height = video.current.videoHeight; canvas.getContext("2d")?.drawImage(video.current, 0, 0); const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, "image/jpeg", .86)); if (blob) { setPendingPhoto(blob); stopCamera(); setState("idle"); } };
  const useGallery = async (file?: File) => { if (!file) return; try { setPendingPhoto(await compressedImage(file)); setState("idle"); } catch { setState("error"); } };
  const save = async () => { if (!pendingPhoto) return; setState("saving"); try { await onSave(pendingPhoto); setPendingPhoto(null); setState("idle"); } catch { setState("error"); } };
  return <section className="rounded-2xl border border-[#e8cda2] bg-[#fff7e8] p-4"><div className="flex items-start gap-3"><Camera className="mt-0.5 text-[#8c1e21]"/><div><p className="eyebrow text-[#a56922]">{bengali ? "নিজের ক্যামেরা" : "Your camera"}</p><h3 className="font-display text-xl font-bold text-[#4a2520]">{bengali ? "এই মুহূর্তটি রাখুন" : "Keep this moment"}</h3><p className="mt-1 text-xs leading-relaxed text-[#75594c]">{bengali ? "ছবিটি শুধু এই ব্রাউজারের ব্যক্তিগত Amar Pujo মেমরিতে থাকবে। কোনও আপলোড, AI বিশ্লেষণ বা পাবলিক গ্যালারি নেই।" : "This photo stays only in this browser’s private Amar Pujo memory. There is no upload, AI analysis, or public gallery."}</p></div></div>{state === "ready" && <video ref={video} muted playsInline className="mt-4 aspect-[4/3] w-full rounded-xl bg-black object-cover"/>}{pendingPhoto && previewUrl && <img src={previewUrl} alt={bengali ? "সেভের আগে ছবি" : "Photo before saving"} className="mt-4 aspect-[4/3] w-full rounded-xl object-cover"/>}<input ref={fileInput} onChange={event => useGallery(event.target.files?.[0])} type="file" accept="image/*" className="hidden" />
    <div className="mt-4 flex flex-wrap gap-2">{state === "ready" ? <><Button onClick={capture} className="bg-[#8c1e21]"><Camera size={16}/>{bengali ? "ছবি তুলুন" : "Capture photo"}</Button><Button onClick={() => { const next = facing === "environment" ? "user" : "environment"; setFacing(next); startCamera(next); }} variant="outline"><SwitchCamera size={16}/>{bengali ? "ক্যামেরা বদলান" : "Switch camera"}</Button><Button onClick={() => { stopCamera(); setState("idle"); }} variant="ghost"><CameraOff size={16}/>{bengali ? "বন্ধ" : "Stop"}</Button></> : pendingPhoto ? <><Button onClick={save} disabled={state === "saving"} className="bg-[#8c1e21]">{state === "saving" ? <Loader2 className="animate-spin" size={16}/> : <Save size={16}/>}{bengali ? "ব্যক্তিগত মেমরি সেভ করুন" : "Save private memory"}</Button><Button onClick={() => setPendingPhoto(null)} variant="outline"><RefreshCw size={16}/>{bengali ? "আবার নিন" : "Retake"}</Button></> : <><Button onClick={() => startCamera()} className="bg-[#8c1e21]"><Camera size={16}/>{bengali ? "ক্যামেরা খুলুন" : "Open camera"}</Button><Button onClick={() => fileInput.current?.click()} variant="outline"><Images size={16}/>{bengali ? "গ্যালারি থেকে নিন" : "Choose from gallery"}</Button></>}</div>
    {(state === "unsupported" || state === "denied" || state === "error") && <p className="mt-3 rounded-xl bg-[#fff0db] p-3 text-sm text-[#704a3a]">{state === "unsupported" ? (bengali ? "এই ব্রাউজারে ক্যামেরা সমর্থিত নয়। গ্যালারি থেকে একটি ছবি বেছে নিন।" : "Camera is not supported in this browser. Choose a photo from your gallery.") : state === "denied" ? (bengali ? "ক্যামেরা অনুমতি বন্ধ আছে। গ্যালারি থেকে একটি ছবি বেছে নিতে পারেন।" : "Camera permission is disabled. You can choose a photo from your gallery.") : (bengali ? "ছবিটি প্রস্তুত করা যায়নি। আবার চেষ্টা করুন বা গ্যালারি ব্যবহার করুন।" : "The photo could not be prepared. Try again or use the gallery.")}</p>}</section>;
}
