import { useMemo, useState } from "react";
import { CheckCircle2, Crosshair, Loader2, MapPin, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AmarPujaCamera } from "@/components/AmarPujaCamera";
import { findNearbyPandals, type NearbyPandal } from "@shared/proximity";
import { trpc } from "@/lib/trpc";
import { addAmarPujaPhoto, createAmarPujaVisit, type AmarPujaVisit, type DetectionMethod } from "@/lib/amarPujaMemories";

type Choice = { id: string; name: string; subArea: string; method: DetectionMethod };
export function CapturePujo({ initialPandalId, bengali, onSaved }: { initialPandalId?: string; bengali: boolean; onSaved?: () => void }) {
  const [query, setQuery] = useState(""); const [nearby, setNearby] = useState<NearbyPandal[]>([]); const [choice, setChoice] = useState<Choice | null>(null); const [visit, setVisit] = useState<AmarPujaVisit | null>(null); const [locationState, setLocationState] = useState<"idle" | "finding" | "denied" | "unavailable">("idle"); const [message, setMessage] = useState<string | null>(null);
  const catalogue = trpc.pandals.list.useQuery(query.trim().length ? { query: query.trim() } : undefined);
  const initialDetail = trpc.pandals.detail.useQuery({ id: initialPandalId ?? "" }, { enabled: Boolean(initialPandalId) });
  const initial = useMemo(() => initialDetail.data?.data ?? null, [initialDetail.data?.data]);
  const chooseNearby = (candidate: NearbyPandal) => setChoice({ id: candidate.id, name: candidate.name, subArea: candidate.subArea, method: "gps_confirmed" });
  const chooseManual = (pandal: { id: string; name: string; subArea: string }) => setChoice({ ...pandal, method: "manual_selection" });
  const findNearby = () => { if (!catalogue.data?.data) { setMessage(bengali ? "পুজোর তালিকা এখনও লোড হচ্ছে। এক মুহূর্ত পরে আবার চেষ্টা করুন।" : "The Pujo catalogue is still loading. Please try again in a moment."); return; } if (!navigator.geolocation) { setLocationState("unavailable"); return; } setMessage(null); setLocationState("finding"); navigator.geolocation.getCurrentPosition(result => { const candidates = findNearbyPandals(catalogue.data.data, { lat: result.coords.latitude, lng: result.coords.longitude }, { radiusMeters: 100, accuracyMeters: result.coords.accuracy }); setNearby(candidates); setLocationState("idle"); }, error => setLocationState(error.code === error.PERMISSION_DENIED ? "denied" : "unavailable"), { enableHighAccuracy: true, timeout: 12_000, maximumAge: 10_000 }); };
  const confirmVisit = async () => { if (!choice) return; try { const saved = await createAmarPujaVisit({ pandalId: choice.id, pandalName: choice.name, subArea: choice.subArea, detectionMethod: choice.method }); setVisit(saved); setMessage(null); onSaved?.(); } catch { setMessage(bengali ? "এই ব্রাউজারে ব্যক্তিগত মেমরি সেভ করা যাচ্ছে না।" : "Private memory storage is unavailable in this browser."); } };
  if (visit) return <div className="mt-5"><div className="rounded-2xl bg-[#3a2020] p-4 text-[#fff7e8]"><CheckCircle2 className="text-[#f3c45e]"/><h2 className="mt-2 font-display text-2xl font-bold">{bengali ? "আপনার সফরটি যোগ হয়েছে" : "Your visit is saved"}</h2><p className="mt-1 text-sm text-[#e9d4bd]">{visit.pandalName} · {bengali ? "এই ব্রাউজারে ব্যক্তিগতভাবে" : "private to this browser"}</p></div><div className="mt-4"><AmarPujaCamera bengali={bengali} onSave={async blob => { await addAmarPujaPhoto({ visitId: visit.id, blob }); onSaved?.(); }} /></div></div>;
  return <section className="mt-5 rounded-[1.5rem] border border-[#e8cda2] bg-[#fffaf0] p-5 sm:p-6"><p className="eyebrow text-[#a56922]">{bengali ? "আমার পুজো মেমরি" : "Amar Pujo memory"}</p><h2 className="mt-1 font-display text-2xl font-bold text-[#4a2520]">{bengali ? "এই পুজোটি নিশ্চিত করুন" : "Confirm this Pujo"}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#75594c]">{bengali ? "কাছাকাছি ফল বা ম্যানুয়াল নির্বাচন কেবল আপনাকে পুজো বাছতে সাহায্য করে। নিশ্চিত না করলে কোনও চেক-ইন তৈরি হয় না এবং সঠিক GPS অবস্থান সংরক্ষণ করা হয় না।" : "Nearby results and manual search only help you choose a Pujo. No check-in is created until you confirm, and precise GPS location is never stored."}</p>
    {initial && !choice && <button onClick={() => chooseManual(initial)} className="mt-4 flex w-full items-center justify-between rounded-xl bg-[#f6e7c9] p-4 text-left"><span><strong className="block text-[#4a2520]">{initial.name}</strong><span className="text-xs text-[#765e53]">{initial.subArea}</span></span><span className="text-xs font-bold text-[#8c1e21]">{bengali ? "এটি বাছুন" : "Select this"}</span></button>}
    {!choice && <><div className="mt-5 flex flex-wrap gap-2"><Button onClick={findNearby} disabled={locationState === "finding"} className="bg-[#8c1e21]"><Crosshair size={16}/>{locationState === "finding" ? <Loader2 className="animate-spin" size={15}/> : null}{bengali ? "কাছাকাছি পুজো খুঁজুন" : "Find nearby Pujos"}</Button></div>{(locationState === "denied" || locationState === "unavailable") && <p className="mt-3 rounded-xl bg-[#fff0db] p-3 text-sm text-[#704a3a]">{locationState === "denied" ? (bengali ? "লোকেশন অনুমতি বন্ধ আছে। নিচে নিজে পুজো বেছে নিন।" : "Location permission is disabled. Choose a Pujo manually below.") : (bengali ? "লাইভ লোকেশন এখন পাওয়া যাচ্ছে না। নিচে নিজে পুজো বেছে নিন।" : "Live location is unavailable. Choose a Pujo manually below.")}</p>}{nearby.length > 0 && <div className="mt-4 space-y-2"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#86644d]">{bengali ? "কাছাকাছি — নিশ্চিত করা দরকার" : "Nearby — confirmation required"}</p>{nearby.map(candidate => <button key={candidate.id} onClick={() => chooseNearby(candidate)} className="flex w-full items-center justify-between rounded-xl border border-[#ead9be] p-3 text-left hover:bg-[#fff4df]"><span><strong className="block text-[#4a2520]">{candidate.name}</strong><span className="text-xs text-[#75594c]">{candidate.subArea} · ~{Math.round(candidate.distanceMeters)} m</span></span><MapPin className="text-[#8c1e21]" size={18}/></button>)}</div>}{nearby.length === 0 && locationState === "idle" && <p className="mt-4 text-sm text-[#75594c]">{bengali ? "কোনও পুজো এখনো খোঁজা হয়নি। অথবা ১০০ মিটারের মধ্যে যাচাই করা কোঅর্ডিনেটসহ পুজো পাওয়া যায়নি।" : "No nearby search has run yet, or no Pujo with verified coordinates was found within 100 metres."}</p>}
      <div className="mt-5 border-t border-[#ead9be] pt-4"><label className="text-xs font-bold uppercase tracking-[.12em] text-[#86644d]">{bengali ? "নিজে খুঁজুন" : "Choose manually"}<div className="mt-2 flex items-center rounded-xl border border-[#dcc2a2] bg-white px-3"><Search size={16} className="text-[#9b7861]"/><input value={query} onChange={event => setQuery(event.target.value)} placeholder={bengali ? "পুজোর নাম বা এলাকা" : "Pujo name or locality"} className="h-11 w-full bg-transparent px-2 text-sm outline-none"/></div></label><div className="mt-2 max-h-52 overflow-y-auto rounded-xl border border-[#ead9be] bg-white">{catalogue.isLoading ? <p className="p-3 text-sm text-[#765e53]">{bengali ? "খোঁজা হচ্ছে…" : "Searching…"}</p> : (catalogue.data?.data ?? []).slice(0, query.trim() ? 12 : 6).map(pandal => <button key={pandal.id} onClick={() => chooseManual(pandal)} className="flex w-full items-center justify-between border-b border-[#f0e3d1] p-3 text-left last:border-0 hover:bg-[#fff7e8]"><span><strong className="block text-sm text-[#4a2520]">{pandal.name}</strong><span className="text-xs text-[#75594c]">{pandal.subArea}</span></span><MapPin size={15} className="text-[#a12424]"/></button>)}</div></div></>}
    {choice && <div className="mt-5 rounded-xl bg-[#f6e7c9] p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#94622a]">{choice.method === "gps_confirmed" ? (bengali ? "কাছাকাছি ফল — আপনার নিশ্চিতকরণ প্রয়োজন" : "Nearby result — your confirmation required") : (bengali ? "ম্যানুয়ালি নির্বাচিত" : "Manually selected")}</p><h3 className="mt-1 font-display text-xl font-bold text-[#4a2520]">{choice.name}</h3><p className="text-sm text-[#75594c]">{choice.subArea}</p><div className="mt-4 flex gap-2"><Button onClick={confirmVisit} className="bg-[#8c1e21]"><ShieldCheck size={16}/>{bengali ? "সফরটি নিশ্চিত করুন" : "Confirm visit"}</Button><Button onClick={() => setChoice(null)} variant="outline">{bengali ? "বদলান" : "Change"}</Button></div></div>}{message && <p className="mt-4 rounded-xl bg-[#fff0db] p-3 text-sm text-[#704a3a]">{message}</p>}</section>;
}
