export interface PujoMusicTrack {
  id: string;
  section: "hits" | "og" | "mahalaya";
  title: string;
  bengaliTitle: string;
  artist: string;
  bengaliArtist: string;
  type: "playlist" | "video" | "search";
  query?: string;
  youtubeId: string;
  thumbnailUrl: string;
  directUrl: string;
  supportsShuffle: boolean;
}

export const PUJO_MUSIC_TRACKS: PujoMusicTrack[] = [
  {
    "id": "hits-full-playlist",
    "section": "hits",
    "title": "Durga Pujo Hits Playlist (106 Tracks)",
    "bengaliTitle": "দুর্গাপুজো হিটস সম্পূর্ণ প্লেলিস্ট (১০৬ গান)",
    "artist": "Monali Thakur, Arijit Singh, Shreya Ghoshal & More",
    "bengaliArtist": "অরিজিৎ সিং, শ্রেয়া ঘোষাল, মোনালী ঠাকুর ও আরও অনেক",
    "type": "video",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://music.youtube.com/playlist?list=PLJAiFJ6bGyew&si=-DCdPqbt80KSHoW-",
    "supportsShuffle": true
  },
  {
    "id": "hit-track-1",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Monali Thakur Guddu",
    "bengaliArtist": "Monali Thakur Guddu",
    "type": "video",
    "query": "Dugga Elo Monali Thakur Guddu",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dugga%20Elo%20Monali%20Thakur%20Guddu",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-2",
    "section": "hits",
    "title": "Bolo Dugga Maiki",
    "bengaliTitle": "Bolo Dugga Maiki",
    "artist": "Arijit Singh Arindom",
    "bengaliArtist": "Arijit Singh Arindom",
    "type": "video",
    "query": "Bolo Dugga Maiki Arijit Singh Arindom",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bolo%20Dugga%20Maiki%20Arijit%20Singh%20Arindom",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-3",
    "section": "hits",
    "title": "Ebar Jeno Onno Rokom Pujo",
    "bengaliTitle": "Ebar Jeno Onno Rokom Pujo",
    "artist": "Nakash Aziz Antara Mitra",
    "bengaliArtist": "Nakash Aziz Antara Mitra",
    "type": "video",
    "query": "Ebar Jeno Onno Rokom Pujo Nakash Aziz Antara Mitra",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Ebar%20Jeno%20Onno%20Rokom%20Pujo%20Nakash%20Aziz%20Antara%20Mitra",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-4",
    "section": "hits",
    "title": "Dhak Baja Kashor Baja",
    "bengaliTitle": "Dhak Baja Kashor Baja",
    "artist": "Shreya Ghoshal",
    "bengaliArtist": "Shreya Ghoshal",
    "type": "video",
    "query": "Dhak Baja Kashor Baja Shreya Ghoshal",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dhak%20Baja%20Kashor%20Baja%20Shreya%20Ghoshal",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-5",
    "section": "hits",
    "title": "Bolo Dugga Elo",
    "bengaliTitle": "Bolo Dugga Elo",
    "artist": "Kaushik-Guddu Sunidhi Chauhan",
    "bengaliArtist": "Kaushik-Guddu Sunidhi Chauhan",
    "type": "video",
    "query": "Bolo Dugga Elo Kaushik-Guddu Sunidhi Chauhan",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bolo%20Dugga%20Elo%20Kaushik-Guddu%20Sunidhi%20Chauhan",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-6",
    "section": "hits",
    "title": "Aamaar Dugga",
    "bengaliTitle": "Aamaar Dugga",
    "artist": "Monali Thakur Anindya Chattopadhyay",
    "bengaliArtist": "Monali Thakur Anindya Chattopadhyay",
    "type": "video",
    "query": "Aamaar Dugga Monali Thakur Anindya Chattopadhyay",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Aamaar%20Dugga%20Monali%20Thakur%20Anindya%20Chattopadhyay",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-7",
    "section": "hits",
    "title": "Dhaker Taley",
    "bengaliTitle": "Dhaker Taley",
    "artist": "Abhijeet Bhattacharya Jeet Gannguli",
    "bengaliArtist": "Abhijeet Bhattacharya Jeet Gannguli",
    "type": "video",
    "query": "Dhaker Taley Abhijeet Bhattacharya Jeet Gannguli",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dhaker%20Taley%20Abhijeet%20Bhattacharya%20Jeet%20Gannguli",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-8",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Akriti Kakar Debanjali B Joshi",
    "bengaliArtist": "Akriti Kakar Debanjali B Joshi",
    "type": "video",
    "query": "Dugga Elo Akriti Kakar Debanjali B Joshi",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dugga%20Elo%20Akriti%20Kakar%20Debanjali%20B%20Joshi",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-9",
    "section": "hits",
    "title": "Shundori Komola",
    "bengaliTitle": "Shundori Komola",
    "artist": "Armaan Malik Villain",
    "bengaliArtist": "Armaan Malik Villain",
    "type": "video",
    "query": "Shundori Komola Armaan Malik Villain",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Shundori%20Komola%20Armaan%20Malik%20Villain",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-10",
    "section": "hits",
    "title": "Elo Je Maa",
    "bengaliTitle": "Elo Je Maa",
    "artist": "Abhijeet Bhattacharya Challenge 2",
    "bengaliArtist": "Abhijeet Bhattacharya Challenge 2",
    "type": "video",
    "query": "Elo Je Maa Abhijeet Bhattacharya Challenge 2",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Elo%20Je%20Maa%20Abhijeet%20Bhattacharya%20Challenge%202",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-11",
    "section": "hits",
    "title": "O Menoka O Menoka",
    "bengaliTitle": "O Menoka O Menoka",
    "artist": "Antara Nandy Ankita Nandy",
    "bengaliArtist": "Antara Nandy Ankita Nandy",
    "type": "video",
    "query": "O Menoka O Menoka Antara Nandy Ankita Nandy",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=O%20Menoka%20O%20Menoka%20Antara%20Nandy%20Ankita%20Nandy",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-12",
    "section": "hits",
    "title": "Ailo Uma Barite",
    "bengaliTitle": "Ailo Uma Barite",
    "artist": "Antara Nandy Monami Ghosh",
    "bengaliArtist": "Antara Nandy Monami Ghosh",
    "type": "video",
    "query": "Ailo Uma Barite Antara Nandy Monami Ghosh",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Ailo%20Uma%20Barite%20Antara%20Nandy%20Monami%20Ghosh",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-13",
    "section": "hits",
    "title": "Uma Ashe Notun Saje",
    "bengaliTitle": "Uma Ashe Notun Saje",
    "artist": "Ankita Bhattacharyya",
    "bengaliArtist": "Ankita Bhattacharyya",
    "type": "video",
    "query": "Uma Ashe Notun Saje Ankita Bhattacharyya",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Uma%20Ashe%20Notun%20Saje%20Ankita%20Bhattacharyya",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-14",
    "section": "hits",
    "title": "Abar Elo Maa",
    "bengaliTitle": "Abar Elo Maa",
    "artist": "Rahul Dutta Ankita Bhattacharyya",
    "bengaliArtist": "Rahul Dutta Ankita Bhattacharyya",
    "type": "video",
    "query": "Abar Elo Maa Rahul Dutta Ankita Bhattacharyya",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Abar%20Elo%20Maa%20Rahul%20Dutta%20Ankita%20Bhattacharyya",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-15",
    "section": "hits",
    "title": "Joy Joy Durga Ma",
    "bengaliTitle": "Joy Joy Durga Ma",
    "artist": "Agnibha Bandopadhyay",
    "bengaliArtist": "Agnibha Bandopadhyay",
    "type": "video",
    "query": "Joy Joy Durga Ma Agnibha Bandopadhyay",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Joy%20Joy%20Durga%20Ma%20Agnibha%20Bandopadhyay",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-16",
    "section": "hits",
    "title": "Durga Maa",
    "bengaliTitle": "Durga Maa",
    "artist": "Akassh Haimanti",
    "bengaliArtist": "Akassh Haimanti",
    "type": "video",
    "query": "Durga Maa Akassh Haimanti",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Durga%20Maa%20Akassh%20Haimanti",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-17",
    "section": "hits",
    "title": "Gouri Elo Dekhe Jalo",
    "bengaliTitle": "Gouri Elo Dekhe Jalo",
    "artist": "Dohar",
    "bengaliArtist": "Dohar",
    "type": "video",
    "query": "Gouri Elo Dekhe Jalo Dohar",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Gouri%20Elo%20Dekhe%20Jalo%20Dohar",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-18",
    "section": "hits",
    "title": "Dhak Baaja Komor Nacha",
    "bengaliTitle": "Dhak Baaja Komor Nacha",
    "artist": "Jeet Akriti Kakar Dev Negi Switzerland",
    "bengaliArtist": "Jeet Akriti Kakar Dev Negi Switzerland",
    "type": "video",
    "query": "Dhak Baaja Komor Nacha Jeet Akriti Kakar Dev Negi Switzerland",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dhak%20Baaja%20Komor%20Nacha%20Jeet%20Akriti%20Kakar%20Dev%20Negi%20Switzerland",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-19",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Asha Bhosle Durga Bandana",
    "bengaliArtist": "Asha Bhosle Durga Bandana",
    "type": "video",
    "query": "Durge Durge Durgatinashini Asha Bhosle Durga Bandana",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Durge%20Durge%20Durgatinashini%20Asha%20Bhosle%20Durga%20Bandana",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-20",
    "section": "hits",
    "title": "Rupang Dehi",
    "bengaliTitle": "Rupang Dehi",
    "artist": "Snita Pramanik Ghosh",
    "bengaliArtist": "Snita Pramanik Ghosh",
    "type": "video",
    "query": "Rupang Dehi Snita Pramanik Ghosh",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Rupang%20Dehi%20Snita%20Pramanik%20Ghosh",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-21",
    "section": "hits",
    "title": "Aigiri Nandini",
    "bengaliTitle": "Aigiri Nandini",
    "artist": "Rajalakshmee Sanjay",
    "bengaliArtist": "Rajalakshmee Sanjay",
    "type": "video",
    "query": "Aigiri Nandini Rajalakshmee Sanjay",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Aigiri%20Nandini%20Rajalakshmee%20Sanjay",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-22",
    "section": "hits",
    "title": "Baja Sanai Aar Baja Re Dhol",
    "bengaliTitle": "Baja Sanai Aar Baja Re Dhol",
    "artist": "Abhijeet Bhattacharya Nilakshi Bhattacharya Dev Sen Deewana",
    "bengaliArtist": "Abhijeet Bhattacharya Nilakshi Bhattacharya Dev Sen Deewana",
    "type": "video",
    "query": "Baja Sanai Aar Baja Re Dhol Abhijeet Bhattacharya Nilakshi Bhattacharya Dev Sen Deewana",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Baja%20Sanai%20Aar%20Baja%20Re%20Dhol%20Abhijeet%20Bhattacharya%20Nilakshi%20Bhattacharya%20Dev%20Sen%20Deewana",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-23",
    "section": "hits",
    "title": "Elo Je Maa",
    "bengaliTitle": "Elo Je Maa",
    "artist": "Abhijeet Bhattacharya Challenge 2",
    "bengaliArtist": "Abhijeet Bhattacharya Challenge 2",
    "type": "video",
    "query": "Elo Je Maa Abhijeet Bhattacharya Challenge 2",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Elo%20Je%20Maa%20Abhijeet%20Bhattacharya%20Challenge%202",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-24",
    "section": "hits",
    "title": "Maa Ashchhe",
    "bengaliTitle": "Maa Ashchhe",
    "artist": "Sanjeev Tiwari",
    "bengaliArtist": "Sanjeev Tiwari",
    "type": "video",
    "query": "Maa Ashchhe Sanjeev Tiwari",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Maa%20Ashchhe%20Sanjeev%20Tiwari",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-25",
    "section": "hits",
    "title": "Esho Maa Durga",
    "bengaliTitle": "Esho Maa Durga",
    "artist": "Shamik Guha Roy Suman Mickey Chatterjee",
    "bengaliArtist": "Shamik Guha Roy Suman Mickey Chatterjee",
    "type": "video",
    "query": "Esho Maa Durga Shamik Guha Roy Suman Mickey Chatterjee",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Esho%20Maa%20Durga%20Shamik%20Guha%20Roy%20Suman%20Mickey%20Chatterjee",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-26",
    "section": "hits",
    "title": "Maa Go Tui",
    "bengaliTitle": "Maa Go Tui",
    "artist": "Somchanda Bhattacharya Manomay Bhattacharyya Durgeshgorer Guptodhon",
    "bengaliArtist": "Somchanda Bhattacharya Manomay Bhattacharyya Durgeshgorer Guptodhon",
    "type": "video",
    "query": "Maa Go Tui Somchanda Bhattacharya Manomay Bhattacharyya Durgeshgorer Guptodhon",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Maa%20Go%20Tui%20Somchanda%20Bhattacharya%20Manomay%20Bhattacharyya%20Durgeshgorer%20Guptodhon",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-27",
    "section": "hits",
    "title": "Jago Uma",
    "bengaliTitle": "Jago Uma",
    "artist": "Rupankar Bagchi Uma",
    "bengaliArtist": "Rupankar Bagchi Uma",
    "type": "video",
    "query": "Jago Uma Rupankar Bagchi Uma",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Jago%20Uma%20Rupankar%20Bagchi%20Uma",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-28",
    "section": "hits",
    "title": "Aigiri Nandini Rock Version",
    "bengaliTitle": "Aigiri Nandini Rock Version",
    "artist": "Sowrabha",
    "bengaliArtist": "Sowrabha",
    "type": "video",
    "query": "Aigiri Nandini Rock Version Sowrabha",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Aigiri%20Nandini%20Rock%20Version%20Sowrabha",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-29",
    "section": "hits",
    "title": "Ailo Uma Barite",
    "bengaliTitle": "Ailo Uma Barite",
    "artist": "Antara Nandy Monami Ghosh",
    "bengaliArtist": "Antara Nandy Monami Ghosh",
    "type": "video",
    "query": "Ailo Uma Barite Antara Nandy Monami Ghosh",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Ailo%20Uma%20Barite%20Antara%20Nandy%20Monami%20Ghosh",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-30",
    "section": "hits",
    "title": "Aaj Baaje",
    "bengaliTitle": "Aaj Baaje",
    "artist": "Somchanda Bhattacharya Durga Sohay",
    "bengaliArtist": "Somchanda Bhattacharya Durga Sohay",
    "type": "video",
    "query": "Aaj Baaje Somchanda Bhattacharya Durga Sohay",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Aaj%20Baaje%20Somchanda%20Bhattacharya%20Durga%20Sohay",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-31",
    "section": "hits",
    "title": "Yoddhar Saathe Ebar Pujo Katan",
    "bengaliTitle": "Yoddhar Saathe Ebar Pujo Katan",
    "artist": "Nakash Aziz Yoddha",
    "bengaliArtist": "Nakash Aziz Yoddha",
    "type": "video",
    "query": "Yoddhar Saathe Ebar Pujo Katan Nakash Aziz Yoddha",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Yoddhar%20Saathe%20Ebar%20Pujo%20Katan%20Nakash%20Aziz%20Yoddha",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-32",
    "section": "hits",
    "title": "Pujo Pujo Gondho",
    "bengaliTitle": "Pujo Pujo Gondho",
    "artist": "Anupam Roy",
    "bengaliArtist": "Anupam Roy",
    "type": "video",
    "query": "Pujo Pujo Gondho Anupam Roy",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Pujo%20Pujo%20Gondho%20Anupam%20Roy",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-33",
    "section": "hits",
    "title": "Pujor Dhaak Theme",
    "bengaliTitle": "Pujor Dhaak Theme",
    "artist": "Bibhabendu Bhattacharya",
    "bengaliArtist": "Bibhabendu Bhattacharya",
    "type": "video",
    "query": "Pujor Dhaak Theme Bibhabendu Bhattacharya",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Pujor%20Dhaak%20Theme%20Bibhabendu%20Bhattacharya",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-34",
    "section": "hits",
    "title": "Jaago Uma",
    "bengaliTitle": "Jaago Uma",
    "artist": "Anupam Roy Rupankar Bagchi Uma",
    "bengaliArtist": "Anupam Roy Rupankar Bagchi Uma",
    "type": "video",
    "query": "Jaago Uma Anupam Roy Rupankar Bagchi Uma",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Jaago%20Uma%20Anupam%20Roy%20Rupankar%20Bagchi%20Uma",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-35",
    "section": "hits",
    "title": "Pujor Gaan",
    "bengaliTitle": "Pujor Gaan",
    "artist": "Poushali Bhattacharya Abritte Talukdar",
    "bengaliArtist": "Poushali Bhattacharya Abritte Talukdar",
    "type": "video",
    "query": "Pujor Gaan Poushali Bhattacharya Abritte Talukdar",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Pujor%20Gaan%20Poushali%20Bhattacharya%20Abritte%20Talukdar",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-36",
    "section": "hits",
    "title": "Aamaar Dugga",
    "bengaliTitle": "Aamaar Dugga",
    "artist": "Monali Thakur Anindya Chattopadhyay",
    "bengaliArtist": "Monali Thakur Anindya Chattopadhyay",
    "type": "video",
    "query": "Aamaar Dugga Monali Thakur Anindya Chattopadhyay",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Aamaar%20Dugga%20Monali%20Thakur%20Anindya%20Chattopadhyay",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-37",
    "section": "hits",
    "title": "Gouri Elo",
    "bengaliTitle": "Gouri Elo",
    "artist": "Dohar Tirtha Bhattacharya Raktabeej",
    "bengaliArtist": "Dohar Tirtha Bhattacharya Raktabeej",
    "type": "video",
    "query": "Gouri Elo Dohar Tirtha Bhattacharya Raktabeej",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Gouri%20Elo%20Dohar%20Tirtha%20Bhattacharya%20Raktabeej",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-38",
    "section": "hits",
    "title": "Aham Rudre",
    "bengaliTitle": "Aham Rudre",
    "artist": "Sourendro Soumyojit Academy of Music",
    "bengaliArtist": "Sourendro Soumyojit Academy of Music",
    "type": "video",
    "query": "Aham Rudre Sourendro Soumyojit Academy of Music",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Aham%20Rudre%20Sourendro%20Soumyojit%20Academy%20of%20Music",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-39",
    "section": "hits",
    "title": "Elo Re Pujo Elo",
    "bengaliTitle": "Elo Re Pujo Elo",
    "artist": "Dabbu Nakash Aziz Senjuti Das",
    "bengaliArtist": "Dabbu Nakash Aziz Senjuti Das",
    "type": "video",
    "query": "Elo Re Pujo Elo Dabbu Nakash Aziz Senjuti Das",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Elo%20Re%20Pujo%20Elo%20Dabbu%20Nakash%20Aziz%20Senjuti%20Das",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-40",
    "section": "hits",
    "title": "Chaarpashe Aalo Hok",
    "bengaliTitle": "Chaarpashe Aalo Hok",
    "artist": "Ajoy Chakrabarty Kaushiki Chakraborty",
    "bengaliArtist": "Ajoy Chakrabarty Kaushiki Chakraborty",
    "type": "video",
    "query": "Chaarpashe Aalo Hok Ajoy Chakrabarty Kaushiki Chakraborty",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Chaarpashe%20Aalo%20Hok%20Ajoy%20Chakrabarty%20Kaushiki%20Chakraborty",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-41",
    "section": "hits",
    "title": "O Thakur",
    "bengaliTitle": "O Thakur",
    "artist": "Upal Sengupta Prosmita Pal Belaseshe",
    "bengaliArtist": "Upal Sengupta Prosmita Pal Belaseshe",
    "type": "video",
    "query": "O Thakur Upal Sengupta Prosmita Pal Belaseshe",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=O%20Thakur%20Upal%20Sengupta%20Prosmita%20Pal%20Belaseshe",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-42",
    "section": "hits",
    "title": "Shubho Shubho",
    "bengaliTitle": "Shubho Shubho",
    "artist": "Altamash Faridi Mrs Chatterjee Vs Norway",
    "bengaliArtist": "Altamash Faridi Mrs Chatterjee Vs Norway",
    "type": "video",
    "query": "Shubho Shubho Altamash Faridi Mrs Chatterjee Vs Norway",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Shubho%20Shubho%20Altamash%20Faridi%20Mrs%20Chatterjee%20Vs%20Norway",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-43",
    "section": "hits",
    "title": "He Maa Durga Maa",
    "bengaliTitle": "He Maa Durga Maa",
    "artist": "Aseema Panda",
    "bengaliArtist": "Aseema Panda",
    "type": "video",
    "query": "He Maa Durga Maa Aseema Panda",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=He%20Maa%20Durga%20Maa%20Aseema%20Panda",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-44",
    "section": "hits",
    "title": "Durga Maa Eseche",
    "bengaliTitle": "Durga Maa Eseche",
    "artist": "Akassh",
    "bengaliArtist": "Akassh",
    "type": "video",
    "query": "Durga Maa Eseche Akassh",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Durga%20Maa%20Eseche%20Akassh",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-45",
    "section": "hits",
    "title": "Eseche Maa Durga Maa DJ Remix",
    "bengaliTitle": "Eseche Maa Durga Maa DJ Remix",
    "artist": "Keshab Dey Ankita Bhattacharyya",
    "bengaliArtist": "Keshab Dey Ankita Bhattacharyya",
    "type": "video",
    "query": "Eseche Maa Durga Maa DJ Remix Keshab Dey Ankita Bhattacharyya",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Eseche%20Maa%20Durga%20Maa%20DJ%20Remix%20Keshab%20Dey%20Ankita%20Bhattacharyya",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-46",
    "section": "hits",
    "title": "Kolki",
    "bengaliTitle": "Kolki",
    "artist": "Monami Ghosh Prativa Dutta Rathijit Bhattacharjee",
    "bengaliArtist": "Monami Ghosh Prativa Dutta Rathijit Bhattacharjee",
    "type": "video",
    "query": "Kolki Monami Ghosh Prativa Dutta Rathijit Bhattacharjee",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Kolki%20Monami%20Ghosh%20Prativa%20Dutta%20Rathijit%20Bhattacharjee",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-47",
    "section": "hits",
    "title": "Dugga Ma Asche",
    "bengaliTitle": "Dugga Ma Asche",
    "artist": "Infra",
    "bengaliArtist": "Infra",
    "type": "video",
    "query": "Dugga Ma Asche Infra",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dugga%20Ma%20Asche%20Infra",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-48",
    "section": "hits",
    "title": "Debi Sajer Gaan",
    "bengaliTitle": "Debi Sajer Gaan",
    "artist": "Rupak Tiary Pragya Dutta",
    "bengaliArtist": "Rupak Tiary Pragya Dutta",
    "type": "video",
    "query": "Debi Sajer Gaan Rupak Tiary Pragya Dutta",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Debi%20Sajer%20Gaan%20Rupak%20Tiary%20Pragya%20Dutta",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-49",
    "section": "hits",
    "title": "Tomake Chai",
    "bengaliTitle": "Tomake Chai",
    "artist": "Arijit Singh Arindom Gangster",
    "bengaliArtist": "Arijit Singh Arindom Gangster",
    "type": "video",
    "query": "Tomake Chai Arijit Singh Arindom Gangster",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Tomake%20Chai%20Arijit%20Singh%20Arindom%20Gangster",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-50",
    "section": "hits",
    "title": "Meri Maa Ke Barabar Koi Nahi",
    "bengaliTitle": "Meri Maa Ke Barabar Koi Nahi",
    "artist": "Jubin Nautiyal",
    "bengaliArtist": "Jubin Nautiyal",
    "type": "video",
    "query": "Meri Maa Ke Barabar Koi Nahi Jubin Nautiyal",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Meri%20Maa%20Ke%20Barabar%20Koi%20Nahi%20Jubin%20Nautiyal",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-51",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Monali Thakur Guddu",
    "bengaliArtist": "Monali Thakur Guddu",
    "type": "video",
    "query": "Dugga Elo Monali Thakur Guddu",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dugga%20Elo%20Monali%20Thakur%20Guddu",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-52",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu",
    "bengaliTitle": "Bajlo Tomar Aalor Benu",
    "artist": "Debolina Nandy Retro Cool Bengali Vol 3",
    "bengaliArtist": "Debolina Nandy Retro Cool Bengali Vol 3",
    "type": "video",
    "query": "Bajlo Tomar Aalor Benu Debolina Nandy Retro Cool Bengali Vol 3",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bajlo%20Tomar%20Aalor%20Benu%20Debolina%20Nandy%20Retro%20Cool%20Bengali%20Vol%203",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-53",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Debolinaa Nandy Retro Cool Bengali",
    "bengaliArtist": "Debolinaa Nandy Retro Cool Bengali",
    "type": "video",
    "query": "Durge Durge Durgatinashini Debolinaa Nandy Retro Cool Bengali",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Durge%20Durge%20Durgatinashini%20Debolinaa%20Nandy%20Retro%20Cool%20Bengali",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-54",
    "section": "hits",
    "title": "Madhukaitava Vidhwangsi",
    "bengaliTitle": "Madhukaitava Vidhwangsi",
    "artist": "Tushar Dutta Trishit Supratik Das Roompa Durga",
    "bengaliArtist": "Tushar Dutta Trishit Supratik Das Roompa Durga",
    "type": "video",
    "query": "Madhukaitava Vidhwangsi Tushar Dutta Trishit Supratik Das Roompa Durga",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Madhukaitava%20Vidhwangsi%20Tushar%20Dutta%20Trishit%20Supratik%20Das%20Roompa%20Durga",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-55",
    "section": "hits",
    "title": "Kalo Jole Kuchla Tole",
    "bengaliTitle": "Kalo Jole Kuchla Tole",
    "artist": "Iman Chakraborty",
    "bengaliArtist": "Iman Chakraborty",
    "type": "video",
    "query": "Kalo Jole Kuchla Tole Iman Chakraborty",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Kalo%20Jole%20Kuchla%20Tole%20Iman%20Chakraborty",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-56",
    "section": "hits",
    "title": "Bajlo Tomar Alor Benu",
    "bengaliTitle": "Bajlo Tomar Alor Benu",
    "artist": "Sriparna Das",
    "bengaliArtist": "Sriparna Das",
    "type": "video",
    "query": "Bajlo Tomar Alor Benu Sriparna Das",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bajlo%20Tomar%20Alor%20Benu%20Sriparna%20Das",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-57",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu",
    "bengaliTitle": "Bajlo Tomar Aalor Benu",
    "artist": "Debolina Nandy",
    "bengaliArtist": "Debolina Nandy",
    "type": "video",
    "query": "Bajlo Tomar Aalor Benu Debolina Nandy",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bajlo%20Tomar%20Aalor%20Benu%20Debolina%20Nandy",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-58",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu With Narration",
    "bengaliTitle": "Bajlo Tomar Aalor Benu With Narration",
    "artist": "Supriti Ghosh",
    "bengaliArtist": "Supriti Ghosh",
    "type": "video",
    "query": "Bajlo Tomar Aalor Benu With Narration Supriti Ghosh",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bajlo%20Tomar%20Aalor%20Benu%20With%20Narration%20Supriti%20Ghosh",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-59",
    "section": "hits",
    "title": "Mahishasura Mardhini",
    "bengaliTitle": "Mahishasura Mardhini",
    "artist": "Sri Vardhini Sharath Shakti",
    "bengaliArtist": "Sri Vardhini Sharath Shakti",
    "type": "video",
    "query": "Mahishasura Mardhini Sri Vardhini Sharath Shakti",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Mahishasura%20Mardhini%20Sri%20Vardhini%20Sharath%20Shakti",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-60",
    "section": "hits",
    "title": "Ya Chandi",
    "bengaliTitle": "Ya Chandi",
    "artist": "Chorus Mahishasura Mardini",
    "bengaliArtist": "Chorus Mahishasura Mardini",
    "type": "video",
    "query": "Ya Chandi Chorus Mahishasura Mardini",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Ya%20Chandi%20Chorus%20Mahishasura%20Mardini",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-61",
    "section": "hits",
    "title": "Jago Tumi Jago",
    "bengaliTitle": "Jago Tumi Jago",
    "artist": "Trissha Chatterjee",
    "bengaliArtist": "Trissha Chatterjee",
    "type": "video",
    "query": "Jago Tumi Jago Trissha Chatterjee",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Jago%20Tumi%20Jago%20Trissha%20Chatterjee",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-62",
    "section": "hits",
    "title": "Borondala Saaja",
    "bengaliTitle": "Borondala Saaja",
    "artist": "Madhuraa Bhattacharya Jeet Gannguli Arundhuti",
    "bengaliArtist": "Madhuraa Bhattacharya Jeet Gannguli Arundhuti",
    "type": "video",
    "query": "Borondala Saaja Madhuraa Bhattacharya Jeet Gannguli Arundhuti",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Borondala%20Saaja%20Madhuraa%20Bhattacharya%20Jeet%20Gannguli%20Arundhuti",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-63",
    "section": "hits",
    "title": "Phagun Haoyay Haoyay",
    "bengaliTitle": "Phagun Haoyay Haoyay",
    "artist": "Jayati Chakraborty Dipanwita Choudhury",
    "bengaliArtist": "Jayati Chakraborty Dipanwita Choudhury",
    "type": "video",
    "query": "Phagun Haoyay Haoyay Jayati Chakraborty Dipanwita Choudhury",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Phagun%20Haoyay%20Haoyay%20Jayati%20Chakraborty%20Dipanwita%20Choudhury",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-64",
    "section": "hits",
    "title": "Ogo Amar Agamani Alo",
    "bengaliTitle": "Ogo Amar Agamani Alo",
    "artist": "Sipra Basu",
    "bengaliArtist": "Sipra Basu",
    "type": "video",
    "query": "Ogo Amar Agamani Alo Sipra Basu",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Ogo%20Amar%20Agamani%20Alo%20Sipra%20Basu",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-65",
    "section": "hits",
    "title": "Raai Jago Go",
    "bengaliTitle": "Raai Jago Go",
    "artist": "Pousali Banerjee",
    "bengaliArtist": "Pousali Banerjee",
    "type": "video",
    "query": "Raai Jago Go Pousali Banerjee",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Raai%20Jago%20Go%20Pousali%20Banerjee",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-66",
    "section": "hits",
    "title": "Rupang Dehi",
    "bengaliTitle": "Rupang Dehi",
    "artist": "Snita Pramanik Ghosh",
    "bengaliArtist": "Snita Pramanik Ghosh",
    "type": "video",
    "query": "Rupang Dehi Snita Pramanik Ghosh",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Rupang%20Dehi%20Snita%20Pramanik%20Ghosh",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-67",
    "section": "hits",
    "title": "Ogo Amar Agomoni Alo",
    "bengaliTitle": "Ogo Amar Agomoni Alo",
    "artist": "Samadrita Ghosh",
    "bengaliArtist": "Samadrita Ghosh",
    "type": "video",
    "query": "Ogo Amar Agomoni Alo Samadrita Ghosh",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Ogo%20Amar%20Agomoni%20Alo%20Samadrita%20Ghosh",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-68",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Asha Bhosle Bou Katha Kao",
    "bengaliArtist": "Asha Bhosle Bou Katha Kao",
    "type": "video",
    "query": "Durge Durge Durgatinashini Asha Bhosle Bou Katha Kao",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Durge%20Durge%20Durgatinashini%20Asha%20Bhosle%20Bou%20Katha%20Kao",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-69",
    "section": "hits",
    "title": "Agomonir Gaan",
    "bengaliTitle": "Agomonir Gaan",
    "artist": "Anupam Roy Oriplast Originals",
    "bengaliArtist": "Anupam Roy Oriplast Originals",
    "type": "video",
    "query": "Agomonir Gaan Anupam Roy Oriplast Originals",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Agomonir%20Gaan%20Anupam%20Roy%20Oriplast%20Originals",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-70",
    "section": "hits",
    "title": "Saajan Rock the Dotara",
    "bengaliTitle": "Saajan Rock the Dotara",
    "artist": "Timir Biswas Iman Chakraborty Durga Sohay",
    "bengaliArtist": "Timir Biswas Iman Chakraborty Durga Sohay",
    "type": "video",
    "query": "Saajan Rock the Dotara Timir Biswas Iman Chakraborty Durga Sohay",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Saajan%20Rock%20the%20Dotara%20Timir%20Biswas%20Iman%20Chakraborty%20Durga%20Sohay",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-71",
    "section": "hits",
    "title": "Pujar Gaan",
    "bengaliTitle": "Pujar Gaan",
    "artist": "Hooligaanism Anirban Bhattacharya",
    "bengaliArtist": "Hooligaanism Anirban Bhattacharya",
    "type": "video",
    "query": "Pujar Gaan Hooligaanism Anirban Bhattacharya",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Pujar%20Gaan%20Hooligaanism%20Anirban%20Bhattacharya",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-72",
    "section": "hits",
    "title": "Asatoma Sadgamaya",
    "bengaliTitle": "Asatoma Sadgamaya",
    "artist": "Arijit Singh Khaad",
    "bengaliArtist": "Arijit Singh Khaad",
    "type": "video",
    "query": "Asatoma Sadgamaya Arijit Singh Khaad",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Asatoma%20Sadgamaya%20Arijit%20Singh%20Khaad",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-73",
    "section": "hits",
    "title": "Gouri Elo",
    "bengaliTitle": "Gouri Elo",
    "artist": "Aritra dasgupta",
    "bengaliArtist": "Aritra dasgupta",
    "type": "video",
    "query": "Gouri Elo Aritra dasgupta",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Gouri%20Elo%20Aritra%20dasgupta",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-74",
    "section": "hits",
    "title": "Doob De Re Mon",
    "bengaliTitle": "Doob De Re Mon",
    "artist": "Nirmalya Roy Abir Chatterjee",
    "bengaliArtist": "Nirmalya Roy Abir Chatterjee",
    "type": "video",
    "query": "Doob De Re Mon Nirmalya Roy Abir Chatterjee",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Doob%20De%20Re%20Mon%20Nirmalya%20Roy%20Abir%20Chatterjee",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-75",
    "section": "hits",
    "title": "Apur Paayer Chhaap",
    "bengaliTitle": "Apur Paayer Chhaap",
    "artist": "Arijit Singh Apur Panchali",
    "bengaliArtist": "Arijit Singh Apur Panchali",
    "type": "video",
    "query": "Apur Paayer Chhaap Arijit Singh Apur Panchali",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Apur%20Paayer%20Chhaap%20Arijit%20Singh%20Apur%20Panchali",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-76",
    "section": "hits",
    "title": "Esho Hey",
    "bengaliTitle": "Esho Hey",
    "artist": "Shreya Ghoshal Ishan Mitra Ek Je Chhilo Raja",
    "bengaliArtist": "Shreya Ghoshal Ishan Mitra Ek Je Chhilo Raja",
    "type": "video",
    "query": "Esho Hey Shreya Ghoshal Ishan Mitra Ek Je Chhilo Raja",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Esho%20Hey%20Shreya%20Ghoshal%20Ishan%20Mitra%20Ek%20Je%20Chhilo%20Raja",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-77",
    "section": "hits",
    "title": "Laage Ura Dhura",
    "bengaliTitle": "Laage Ura Dhura",
    "artist": "Pritom Hasan Debosrie Antara Toofan",
    "bengaliArtist": "Pritom Hasan Debosrie Antara Toofan",
    "type": "video",
    "query": "Laage Ura Dhura Pritom Hasan Debosrie Antara Toofan",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Laage%20Ura%20Dhura%20Pritom%20Hasan%20Debosrie%20Antara%20Toofan",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-78",
    "section": "hits",
    "title": "Bholey Baba",
    "bengaliTitle": "Bholey Baba",
    "artist": "Badshah Nikhita Gandhi",
    "bengaliArtist": "Badshah Nikhita Gandhi",
    "type": "video",
    "query": "Bholey Baba Badshah Nikhita Gandhi",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bholey%20Baba%20Badshah%20Nikhita%20Gandhi",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-79",
    "section": "hits",
    "title": "Dushtu Kokil",
    "bengaliTitle": "Dushtu Kokil",
    "artist": "Kona Akassh Toofan",
    "bengaliArtist": "Kona Akassh Toofan",
    "type": "video",
    "query": "Dushtu Kokil Kona Akassh Toofan",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Dushtu%20Kokil%20Kona%20Akassh%20Toofan",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-80",
    "section": "hits",
    "title": "Mala Re",
    "bengaliTitle": "Mala Re",
    "artist": "Jeet Gannguli Romeo",
    "bengaliArtist": "Jeet Gannguli Romeo",
    "type": "video",
    "query": "Mala Re Jeet Gannguli Romeo",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Mala%20Re%20Jeet%20Gannguli%20Romeo",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-81",
    "section": "hits",
    "title": "Koka Kola",
    "bengaliTitle": "Koka Kola",
    "artist": "Samidh Mukherjee Kalpona Patoary",
    "bengaliArtist": "Samidh Mukherjee Kalpona Patoary",
    "type": "video",
    "query": "Koka Kola Samidh Mukherjee Kalpona Patoary",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Koka%20Kola%20Samidh%20Mukherjee%20Kalpona%20Patoary",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-82",
    "section": "hits",
    "title": "Michhrir Dana",
    "bengaliTitle": "Michhrir Dana",
    "artist": "Shreya Ghoshal Jeet Gannguli Bibaho Obhijaan",
    "bengaliArtist": "Shreya Ghoshal Jeet Gannguli Bibaho Obhijaan",
    "type": "video",
    "query": "Michhrir Dana Shreya Ghoshal Jeet Gannguli Bibaho Obhijaan",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Michhrir%20Dana%20Shreya%20Ghoshal%20Jeet%20Gannguli%20Bibaho%20Obhijaan",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-83",
    "section": "hits",
    "title": "Desi Chhori",
    "bengaliTitle": "Desi Chhori",
    "artist": "Satrujit Sen Neha Kakkar Yoddha",
    "bengaliArtist": "Satrujit Sen Neha Kakkar Yoddha",
    "type": "video",
    "query": "Desi Chhori Satrujit Sen Neha Kakkar Yoddha",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Desi%20Chhori%20Satrujit%20Sen%20Neha%20Kakkar%20Yoddha",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-84",
    "section": "hits",
    "title": "Party Shoes",
    "bengaliTitle": "Party Shoes",
    "artist": "Shadaab Hashmi Neha Kakkar Bindaas",
    "bengaliArtist": "Shadaab Hashmi Neha Kakkar Bindaas",
    "type": "video",
    "query": "Party Shoes Shadaab Hashmi Neha Kakkar Bindaas",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Party%20Shoes%20Shadaab%20Hashmi%20Neha%20Kakkar%20Bindaas",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-85",
    "section": "hits",
    "title": "Bujhina Toh Tai",
    "bengaliTitle": "Bujhina Toh Tai",
    "artist": "Nusraat Faria Mumzy Stranger",
    "bengaliArtist": "Nusraat Faria Mumzy Stranger",
    "type": "video",
    "query": "Bujhina Toh Tai Nusraat Faria Mumzy Stranger",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Bujhina%20Toh%20Tai%20Nusraat%20Faria%20Mumzy%20Stranger",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-86",
    "section": "hits",
    "title": "Lady Killer Romeo",
    "bengaliTitle": "Lady Killer Romeo",
    "artist": "Jeet Gannguli Romeo",
    "bengaliArtist": "Jeet Gannguli Romeo",
    "type": "video",
    "query": "Lady Killer Romeo Jeet Gannguli Romeo",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Lady%20Killer%20Romeo%20Jeet%20Gannguli%20Romeo",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-87",
    "section": "hits",
    "title": "Police Chorer Preme Porechhe",
    "bengaliTitle": "Police Chorer Preme Porechhe",
    "artist": "Jeet Gannguli Abhijeet Akriti Kakar Challenge 2",
    "bengaliArtist": "Jeet Gannguli Abhijeet Akriti Kakar Challenge 2",
    "type": "video",
    "query": "Police Chorer Preme Porechhe Jeet Gannguli Abhijeet Akriti Kakar Challenge 2",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Police%20Chorer%20Preme%20Porechhe%20Jeet%20Gannguli%20Abhijeet%20Akriti%20Kakar%20Challenge%202",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-88",
    "section": "hits",
    "title": "Baundule Ghuri",
    "bengaliTitle": "Baundule Ghuri",
    "artist": "Anupam Roy Arijit Singh Shreya Ghoshal Dawshom Awbotaar",
    "bengaliArtist": "Anupam Roy Arijit Singh Shreya Ghoshal Dawshom Awbotaar",
    "type": "video",
    "query": "Baundule Ghuri Anupam Roy Arijit Singh Shreya Ghoshal Dawshom Awbotaar",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Baundule%20Ghuri%20Anupam%20Roy%20Arijit%20Singh%20Shreya%20Ghoshal%20Dawshom%20Awbotaar",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-89",
    "section": "hits",
    "title": "Tumi Jantei Paro Naa",
    "bengaliTitle": "Tumi Jantei Paro Naa",
    "artist": "Mahtim Shakib Cheeni 2",
    "bengaliArtist": "Mahtim Shakib Cheeni 2",
    "type": "video",
    "query": "Tumi Jantei Paro Naa Mahtim Shakib Cheeni 2",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Tumi%20Jantei%20Paro%20Naa%20Mahtim%20Shakib%20Cheeni%202",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-90",
    "section": "hits",
    "title": "Taakey Olpo Kachhe Dakchhi",
    "bengaliTitle": "Taakey Olpo Kachhe Dakchhi",
    "artist": "Mahtim Shakib Prem Tame",
    "bengaliArtist": "Mahtim Shakib Prem Tame",
    "type": "video",
    "query": "Taakey Olpo Kachhe Dakchhi Mahtim Shakib Prem Tame",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Taakey%20Olpo%20Kachhe%20Dakchhi%20Mahtim%20Shakib%20Prem%20Tame",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-91",
    "section": "hits",
    "title": "Egiye De",
    "bengaliTitle": "Egiye De",
    "artist": "Arijit Singh Madhubanti Bagchi Arindom",
    "bengaliArtist": "Arijit Singh Madhubanti Bagchi Arindom",
    "type": "video",
    "query": "Egiye De Arijit Singh Madhubanti Bagchi Arindom",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Egiye%20De%20Arijit%20Singh%20Madhubanti%20Bagchi%20Arindom",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-92",
    "section": "hits",
    "title": "Shudhu Tomari Jonyo Theme",
    "bengaliTitle": "Shudhu Tomari Jonyo Theme",
    "artist": "Arijit Singh Shreya Ghoshal",
    "bengaliArtist": "Arijit Singh Shreya Ghoshal",
    "type": "video",
    "query": "Shudhu Tomari Jonyo Theme Arijit Singh Shreya Ghoshal",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Shudhu%20Tomari%20Jonyo%20Theme%20Arijit%20Singh%20Shreya%20Ghoshal",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-93",
    "section": "hits",
    "title": "Amake Nao",
    "bengaliTitle": "Amake Nao",
    "artist": "Debayan Banerjee Srikanto",
    "bengaliArtist": "Debayan Banerjee Srikanto",
    "type": "video",
    "query": "Amake Nao Debayan Banerjee Srikanto",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Amake%20Nao%20Debayan%20Banerjee%20Srikanto",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-94",
    "section": "hits",
    "title": "Sajani",
    "bengaliTitle": "Sajani",
    "artist": "Nilayan Chatterjee Dilkhush",
    "bengaliArtist": "Nilayan Chatterjee Dilkhush",
    "type": "video",
    "query": "Sajani Nilayan Chatterjee Dilkhush",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Sajani%20Nilayan%20Chatterjee%20Dilkhush",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-95",
    "section": "hits",
    "title": "Pheshey Jaai",
    "bengaliTitle": "Pheshey Jaai",
    "artist": "Habib Wahid Shithi Saha Arafat Mohsin Toofan",
    "bengaliArtist": "Habib Wahid Shithi Saha Arafat Mohsin Toofan",
    "type": "video",
    "query": "Pheshey Jaai Habib Wahid Shithi Saha Arafat Mohsin Toofan",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Pheshey%20Jaai%20Habib%20Wahid%20Shithi%20Saha%20Arafat%20Mohsin%20Toofan",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-96",
    "section": "hits",
    "title": "Ure Geche",
    "bengaliTitle": "Ure Geche",
    "artist": "Ash King Monali Thakur Parbona Ami Charte Toke",
    "bengaliArtist": "Ash King Monali Thakur Parbona Ami Charte Toke",
    "type": "video",
    "query": "Ure Geche Ash King Monali Thakur Parbona Ami Charte Toke",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Ure%20Geche%20Ash%20King%20Monali%20Thakur%20Parbona%20Ami%20Charte%20Toke",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-97",
    "section": "hits",
    "title": "Aashona",
    "bengaliTitle": "Aashona",
    "artist": "Arijit Singh Prashmita Paul Arindom Borbaad",
    "bengaliArtist": "Arijit Singh Prashmita Paul Arindom Borbaad",
    "type": "video",
    "query": "Aashona Arijit Singh Prashmita Paul Arindom Borbaad",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Aashona%20Arijit%20Singh%20Prashmita%20Paul%20Arindom%20Borbaad",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-98",
    "section": "hits",
    "title": "Era Sukher Laagi",
    "bengaliTitle": "Era Sukher Laagi",
    "artist": "Chorus Debojyoti Mishra Chokher Bali",
    "bengaliArtist": "Chorus Debojyoti Mishra Chokher Bali",
    "type": "video",
    "query": "Era Sukher Laagi Chorus Debojyoti Mishra Chokher Bali",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Era%20Sukher%20Laagi%20Chorus%20Debojyoti%20Mishra%20Chokher%20Bali",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-99",
    "section": "hits",
    "title": "Tumi Aashe Paashe",
    "bengaliTitle": "Tumi Aashe Paashe",
    "artist": "Nakash Aziz Monali Thakur Parbona Ami Charte Toke",
    "bengaliArtist": "Nakash Aziz Monali Thakur Parbona Ami Charte Toke",
    "type": "video",
    "query": "Tumi Aashe Paashe Nakash Aziz Monali Thakur Parbona Ami Charte Toke",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Tumi%20Aashe%20Paashe%20Nakash%20Aziz%20Monali%20Thakur%20Parbona%20Ami%20Charte%20Toke",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-100",
    "section": "hits",
    "title": "Hey Shokha",
    "bengaliTitle": "Hey Shokha",
    "artist": "Somlata Acharyya Chowdhury Arindom",
    "bengaliArtist": "Somlata Acharyya Chowdhury Arindom",
    "type": "video",
    "query": "Hey Shokha Somlata Acharyya Chowdhury Arindom",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Hey%20Shokha%20Somlata%20Acharyya%20Chowdhury%20Arindom",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-101",
    "section": "hits",
    "title": "Shaajo Shaajao",
    "bengaliTitle": "Shaajo Shaajao",
    "artist": "Sahana Bajpaie Ballabhpurer Roopkotha",
    "bengaliArtist": "Sahana Bajpaie Ballabhpurer Roopkotha",
    "type": "video",
    "query": "Shaajo Shaajao Sahana Bajpaie Ballabhpurer Roopkotha",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Shaajo%20Shaajao%20Sahana%20Bajpaie%20Ballabhpurer%20Roopkotha",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-102",
    "section": "hits",
    "title": "Notun Premer Gaan",
    "bengaliTitle": "Notun Premer Gaan",
    "artist": "Debraj Bhattacharya Surangana Bandyopadhyay Ballabhpurer Roopkotha",
    "bengaliArtist": "Debraj Bhattacharya Surangana Bandyopadhyay Ballabhpurer Roopkotha",
    "type": "video",
    "query": "Notun Premer Gaan Debraj Bhattacharya Surangana Bandyopadhyay Ballabhpurer Roopkotha",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Notun%20Premer%20Gaan%20Debraj%20Bhattacharya%20Surangana%20Bandyopadhyay%20Ballabhpurer%20Roopkotha",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-103",
    "section": "hits",
    "title": "Tumi Emni Emni Esho",
    "bengaliTitle": "Tumi Emni Emni Esho",
    "artist": "Sanchita Bhowmick Tamalika Golder Swadesh Misra Durgo Rawhoshyo",
    "bengaliArtist": "Sanchita Bhowmick Tamalika Golder Swadesh Misra Durgo Rawhoshyo",
    "type": "video",
    "query": "Tumi Emni Emni Esho Sanchita Bhowmick Tamalika Golder Swadesh Misra Durgo Rawhoshyo",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Tumi%20Emni%20Emni%20Esho%20Sanchita%20Bhowmick%20Tamalika%20Golder%20Swadesh%20Misra%20Durgo%20Rawhoshyo",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-104",
    "section": "hits",
    "title": "Maa Go Tui",
    "bengaliTitle": "Maa Go Tui",
    "artist": "Shovan Ganguly Durgapujor Gaan",
    "bengaliArtist": "Shovan Ganguly Durgapujor Gaan",
    "type": "video",
    "query": "Maa Go Tui Shovan Ganguly Durgapujor Gaan",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Maa%20Go%20Tui%20Shovan%20Ganguly%20Durgapujor%20Gaan",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-105",
    "section": "hits",
    "title": "Khoka Babu",
    "bengaliTitle": "Khoka Babu",
    "artist": "Rishi Samidh Sedin Dekha Hoyechilo",
    "bengaliArtist": "Rishi Samidh Sedin Dekha Hoyechilo",
    "type": "video",
    "query": "Khoka Babu Rishi Samidh Sedin Dekha Hoyechilo",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Khoka%20Babu%20Rishi%20Samidh%20Sedin%20Dekha%20Hoyechilo",
    "supportsShuffle": false
  },
  {
    "id": "hit-track-106",
    "section": "hits",
    "title": "Pyaar Ka Bukhaar",
    "bengaliTitle": "Pyaar Ka Bukhaar",
    "artist": "Jeet Gannguli Suraj Jagan Challenge 2",
    "bengaliArtist": "Jeet Gannguli Suraj Jagan Challenge 2",
    "type": "video",
    "query": "Pyaar Ka Bukhaar Jeet Gannguli Suraj Jagan Challenge 2",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/results?search_query=Pyaar%20Ka%20Bukhaar%20Jeet%20Gannguli%20Suraj%20Jagan%20Challenge%202",
    "supportsShuffle": false
  },
  {
    "id": "og-single",
    "section": "og",
    "title": "Durga Pujo OG (Dugga Elo)",
    "bengaliTitle": "দুর্গাপুজো ওজি (দুগ্গা এলো)",
    "artist": "Classic Evergreen Pujo Gaan",
    "bengaliArtist": "চিরসবুজ মেলোডি ও পুজো সুর",
    "type": "video",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://music.youtube.com/watch?v=oyBQywMMi24&si=x0pifg0r0CsNqRXg",
    "supportsShuffle": false
  },
  {
    "id": "mahalaya-original",
    "section": "mahalaya",
    "title": "Mahishasuramardini (Original)",
    "bengaliTitle": "মহিষাসুরমর্দিনী (বীরেন্দ্রকৃষ্ণ ভদ্র)",
    "artist": "Birendra Krishna Bhadra & Pankaj Mullick",
    "bengaliArtist": "বীরেন্দ্রকৃষ্ণ ভদ্র ও পঙ্কজ মল্লিক",
    "type": "video",
    "youtubeId": "Oxs4vBNkqtM",
    "thumbnailUrl": "https://img.youtube.com/vi/Oxs4vBNkqtM/hqdefault.jpg",
    "directUrl": "https://music.youtube.com/watch?v=Oxs4vBNkqtM&si=rO8k3_vfsdggGmyl",
    "supportsShuffle": false
  },
  {
    "id": "mahalaya-playlist",
    "section": "mahalaya",
    "title": "Mahalaya Special Playlist",
    "bengaliTitle": "মহালয়া বিশেষ প্লেলিস্ট",
    "artist": "Mahalaya Songs & Chandi Path",
    "bengaliArtist": "মহালয়া ও আগমনী চণ্ডীপাঠ সংকলন",
    "type": "video",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://music.youtube.com/playlist?list=PLORF1mEtpAB8&si=fN_ZwGRhtL8MaOZC",
    "supportsShuffle": true
  }
];
