export interface PujoMusicTrack {
  id: string;
  section: "hits" | "og" | "mahalaya";
  title: string;
  bengaliTitle: string;
  artist: string;
  bengaliArtist: string;
  type: "playlist" | "video" | "search";
  query?: string;
  youtubeId: string;
  thumbnailUrl: string;
  directUrl: string;
  supportsShuffle: boolean;
  durationSeconds?: number;
}

export const PUJO_MUSIC_TRACKS: PujoMusicTrack[] = [
  {
    "id": "hit-song-1",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Monali Thakur, Guddu",
    "bengaliArtist": "Monali Thakur, Guddu",
    "type": "video",
    "youtubeId": "xlElO06nQy8",
    "thumbnailUrl": "https://img.youtube.com/vi/xlElO06nQy8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xlElO06nQy8",
    "supportsShuffle": false,
    "durationSeconds": 215
  },
  {
    "id": "hit-song-2",
    "section": "hits",
    "title": "Bolo Dugga Maiki (song \"Dugga Ma\")",
    "bengaliTitle": "Bolo Dugga Maiki (song \"Dugga Ma\")",
    "artist": "Arijit Singh, Arindom",
    "bengaliArtist": "Arijit Singh, Arindom",
    "type": "video",
    "youtubeId": "sPuZ0Q3KDWo",
    "thumbnailUrl": "https://img.youtube.com/vi/sPuZ0Q3KDWo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=sPuZ0Q3KDWo",
    "supportsShuffle": false,
    "durationSeconds": 248
  },
  {
    "id": "hit-song-3",
    "section": "hits",
    "title": "Ebar Jeno Onno Rokom Pujo",
    "bengaliTitle": "Ebar Jeno Onno Rokom Pujo",
    "artist": "Nakash Aziz, Antara Mitra (Yoddha)",
    "bengaliArtist": "Nakash Aziz, Antara Mitra (Yoddha)",
    "type": "video",
    "youtubeId": "be1l6wWKUEg",
    "thumbnailUrl": "https://img.youtube.com/vi/be1l6wWKUEg/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=be1l6wWKUEg",
    "supportsShuffle": false,
    "durationSeconds": 272
  },
  {
    "id": "hit-song-4",
    "section": "hits",
    "title": "Dhak Baja Kashor Baja",
    "bengaliTitle": "Dhak Baja Kashor Baja",
    "artist": "Shreya Ghoshal",
    "bengaliArtist": "Shreya Ghoshal",
    "type": "video",
    "youtubeId": "rwyqFCznhZk",
    "thumbnailUrl": "https://img.youtube.com/vi/rwyqFCznhZk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=rwyqFCznhZk",
    "supportsShuffle": false,
    "durationSeconds": 198
  },
  {
    "id": "hit-song-5",
    "section": "hits",
    "title": "Bolo Dugga Elo (song \"Dugga Dugga\")",
    "bengaliTitle": "Bolo Dugga Elo (song \"Dugga Dugga\")",
    "artist": "Sunidhi Chauhan, Kaushik-Guddu",
    "bengaliArtist": "Sunidhi Chauhan, Kaushik-Guddu",
    "type": "video",
    "youtubeId": "PiMa4BW9Vrw",
    "thumbnailUrl": "https://img.youtube.com/vi/PiMa4BW9Vrw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=PiMa4BW9Vrw",
    "supportsShuffle": false,
    "durationSeconds": 225
  },
  {
    "id": "hit-song-6",
    "section": "hits",
    "title": "Aamaar Dugga",
    "bengaliTitle": "Aamaar Dugga",
    "artist": "Monali Thakur, Anindya Chattopadhyay",
    "bengaliArtist": "Monali Thakur, Anindya Chattopadhyay",
    "type": "video",
    "youtubeId": "4h5DXcN6cd4",
    "thumbnailUrl": "https://img.youtube.com/vi/4h5DXcN6cd4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=4h5DXcN6cd4",
    "supportsShuffle": false,
    "durationSeconds": 260
  },
  {
    "id": "hit-song-7",
    "section": "hits",
    "title": "Dhaker Taley",
    "bengaliTitle": "Dhaker Taley",
    "artist": "Abhijeet Bhattacharya, Jeet Gannguli (Poran Jai Jolia Re)",
    "bengaliArtist": "Abhijeet Bhattacharya, Jeet Gannguli (Poran Jai Jolia Re)",
    "type": "video",
    "youtubeId": "hbXuXt7gkFY",
    "thumbnailUrl": "https://img.youtube.com/vi/hbXuXt7gkFY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=hbXuXt7gkFY",
    "supportsShuffle": false,
    "durationSeconds": 284
  },
  {
    "id": "hit-song-8",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Akriti Kakar, Debanjali B Joshi",
    "bengaliArtist": "Akriti Kakar, Debanjali B Joshi",
    "type": "video",
    "youtubeId": "xytF80lvSV8",
    "thumbnailUrl": "https://img.youtube.com/vi/xytF80lvSV8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xytF80lvSV8",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-9",
    "section": "hits",
    "title": "Shundori Komola",
    "bengaliTitle": "Shundori Komola",
    "artist": "Armaan Malik, Antara Mitra (Villain)",
    "bengaliArtist": "Armaan Malik, Antara Mitra (Villain)",
    "type": "video",
    "youtubeId": "gwjWIawYyNs",
    "thumbnailUrl": "https://img.youtube.com/vi/gwjWIawYyNs/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=gwjWIawYyNs",
    "supportsShuffle": false,
    "durationSeconds": 238
  },
  {
    "id": "hit-song-10",
    "section": "hits",
    "title": "Elo Je Maa",
    "bengaliTitle": "Elo Je Maa",
    "artist": "Abhijeet Bhattacharya (Challenge 2)",
    "bengaliArtist": "Abhijeet Bhattacharya (Challenge 2)",
    "type": "video",
    "youtubeId": "2U416kTo0as",
    "thumbnailUrl": "https://img.youtube.com/vi/2U416kTo0as/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=2U416kTo0as",
    "supportsShuffle": false,
    "durationSeconds": 255
  },
  {
    "id": "hit-song-11",
    "section": "hits",
    "title": "O Menoka O Menoka",
    "bengaliTitle": "O Menoka O Menoka",
    "artist": "Antara Nandy, Ankita Nandy",
    "bengaliArtist": "Antara Nandy, Ankita Nandy",
    "type": "video",
    "youtubeId": "xUMhpMmwAmM",
    "thumbnailUrl": "https://img.youtube.com/vi/xUMhpMmwAmM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xUMhpMmwAmM",
    "supportsShuffle": false,
    "durationSeconds": 215
  },
  {
    "id": "hit-song-12",
    "section": "hits",
    "title": "Ailo Uma Barite",
    "bengaliTitle": "Ailo Uma Barite",
    "artist": "Antara Nandy, Monami Ghosh",
    "bengaliArtist": "Antara Nandy, Monami Ghosh",
    "type": "video",
    "youtubeId": "0xDe5O7kAC0",
    "thumbnailUrl": "https://img.youtube.com/vi/0xDe5O7kAC0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=0xDe5O7kAC0",
    "supportsShuffle": false,
    "durationSeconds": 248
  },
  {
    "id": "hit-song-13",
    "section": "hits",
    "title": "Uma Ashe Notun Saje",
    "bengaliTitle": "Uma Ashe Notun Saje",
    "artist": "Ankita Bhattacharyya",
    "bengaliArtist": "Ankita Bhattacharyya",
    "type": "video",
    "youtubeId": "hnkfDCbULxk",
    "thumbnailUrl": "https://img.youtube.com/vi/hnkfDCbULxk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=hnkfDCbULxk",
    "supportsShuffle": false,
    "durationSeconds": 272
  },
  {
    "id": "hit-song-14",
    "section": "hits",
    "title": "Abar Elo Maa",
    "bengaliTitle": "Abar Elo Maa",
    "artist": "Rahul Dutta, Ankita Bhattacharyya",
    "bengaliArtist": "Rahul Dutta, Ankita Bhattacharyya",
    "type": "video",
    "youtubeId": "FH-p9rnBbU4",
    "thumbnailUrl": "https://img.youtube.com/vi/FH-p9rnBbU4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=FH-p9rnBbU4",
    "supportsShuffle": false,
    "durationSeconds": 198
  },
  {
    "id": "hit-song-15",
    "section": "hits",
    "title": "Joy Joy Durga Ma",
    "bengaliTitle": "Joy Joy Durga Ma",
    "artist": "Agnibha Bandopadhyay",
    "bengaliArtist": "Agnibha Bandopadhyay",
    "type": "video",
    "youtubeId": "3E_qefwPA0E",
    "thumbnailUrl": "https://img.youtube.com/vi/3E_qefwPA0E/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=3E_qefwPA0E",
    "supportsShuffle": false,
    "durationSeconds": 225
  },
  {
    "id": "hit-song-16",
    "section": "hits",
    "title": "Durga Maa",
    "bengaliTitle": "Durga Maa",
    "artist": "Akassh, Haimanti",
    "bengaliArtist": "Akassh, Haimanti",
    "type": "video",
    "youtubeId": "9OkzYV4R9nc",
    "thumbnailUrl": "https://img.youtube.com/vi/9OkzYV4R9nc/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=9OkzYV4R9nc",
    "supportsShuffle": false,
    "durationSeconds": 260
  },
  {
    "id": "hit-song-17",
    "section": "hits",
    "title": "Gouri Elo Dekhe Jalo",
    "bengaliTitle": "Gouri Elo Dekhe Jalo",
    "artist": "Dohar",
    "bengaliArtist": "Dohar",
    "type": "video",
    "youtubeId": "W-YAf-bHkCw",
    "thumbnailUrl": "https://img.youtube.com/vi/W-YAf-bHkCw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=W-YAf-bHkCw",
    "supportsShuffle": false,
    "durationSeconds": 284
  },
  {
    "id": "hit-song-18",
    "section": "hits",
    "title": "Dhak Baaja Komor Nacha",
    "bengaliTitle": "Dhak Baaja Komor Nacha",
    "artist": "Jeet, Akriti Kakar, Dev Negi (Switzerland)",
    "bengaliArtist": "Jeet, Akriti Kakar, Dev Negi (Switzerland)",
    "type": "video",
    "youtubeId": "G7CdEseBpwc",
    "thumbnailUrl": "https://img.youtube.com/vi/G7CdEseBpwc/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=G7CdEseBpwc",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-19",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Asha Bhosle (Durga Bandana)",
    "bengaliArtist": "Asha Bhosle (Durga Bandana)",
    "type": "video",
    "youtubeId": "MMkXLPPSnwM",
    "thumbnailUrl": "https://img.youtube.com/vi/MMkXLPPSnwM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=MMkXLPPSnwM",
    "supportsShuffle": false,
    "durationSeconds": 238
  },
  {
    "id": "hit-song-20",
    "section": "hits",
    "title": "Rupang Dehi",
    "bengaliTitle": "Rupang Dehi",
    "artist": "Snita Pramanik Ghosh",
    "bengaliArtist": "Snita Pramanik Ghosh",
    "type": "video",
    "youtubeId": "IbDqRfeqjDo",
    "thumbnailUrl": "https://img.youtube.com/vi/IbDqRfeqjDo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=IbDqRfeqjDo",
    "supportsShuffle": false,
    "durationSeconds": 255
  },
  {
    "id": "hit-song-21",
    "section": "hits",
    "title": "Aigiri Nandini",
    "bengaliTitle": "Aigiri Nandini",
    "artist": "Rajalakshmee Sanjay",
    "bengaliArtist": "Rajalakshmee Sanjay",
    "type": "video",
    "youtubeId": "1Yycc3tejNw",
    "thumbnailUrl": "https://img.youtube.com/vi/1Yycc3tejNw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=1Yycc3tejNw",
    "supportsShuffle": false,
    "durationSeconds": 215
  },
  {
    "id": "hit-song-22",
    "section": "hits",
    "title": "Baja Sanai Aar Baja Re Dhol",
    "bengaliTitle": "Baja Sanai Aar Baja Re Dhol",
    "artist": "Abhijeet, Nilakshi Bhattacharya, Dev Sen (Deewana)",
    "bengaliArtist": "Abhijeet, Nilakshi Bhattacharya, Dev Sen (Deewana)",
    "type": "video",
    "youtubeId": "H9puHH3wlqs",
    "thumbnailUrl": "https://img.youtube.com/vi/H9puHH3wlqs/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=H9puHH3wlqs",
    "supportsShuffle": false,
    "durationSeconds": 248
  },
  {
    "id": "hit-song-23",
    "section": "hits",
    "title": "Elo Je Maa",
    "bengaliTitle": "Elo Je Maa",
    "artist": "Abhijeet Bhattacharya (Challenge 2) — duplicate of #10",
    "bengaliArtist": "Abhijeet Bhattacharya (Challenge 2) — duplicate of #10",
    "type": "video",
    "youtubeId": "2U416kTo0as",
    "thumbnailUrl": "https://img.youtube.com/vi/2U416kTo0as/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=2U416kTo0as",
    "supportsShuffle": false,
    "durationSeconds": 272
  },
  {
    "id": "hit-song-24",
    "section": "hits",
    "title": "Maa Ashchhe",
    "bengaliTitle": "Maa Ashchhe",
    "artist": "Sanjeev Tiwari",
    "bengaliArtist": "Sanjeev Tiwari",
    "type": "video",
    "youtubeId": "Icgq6OE7b30",
    "thumbnailUrl": "https://img.youtube.com/vi/Icgq6OE7b30/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Icgq6OE7b30",
    "supportsShuffle": false,
    "durationSeconds": 198
  },
  {
    "id": "hit-song-25",
    "section": "hits",
    "title": "Esho Maa Durga",
    "bengaliTitle": "Esho Maa Durga",
    "artist": "Shamik Guha Roy, Suman Mickey Chatterjee",
    "bengaliArtist": "Shamik Guha Roy, Suman Mickey Chatterjee",
    "type": "video",
    "youtubeId": "bQtuffhU6_4",
    "thumbnailUrl": "https://img.youtube.com/vi/bQtuffhU6_4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=bQtuffhU6_4",
    "supportsShuffle": false,
    "durationSeconds": 225
  },
  {
    "id": "hit-song-26",
    "section": "hits",
    "title": "Maa Go Tui",
    "bengaliTitle": "Maa Go Tui",
    "artist": "Somchanda Bhattacharya, Manomay Bhattacharyya (Durgeshgorer Guptodhon)",
    "bengaliArtist": "Somchanda Bhattacharya, Manomay Bhattacharyya (Durgeshgorer Guptodhon)",
    "type": "video",
    "youtubeId": "60tSbJWJCr0",
    "thumbnailUrl": "https://img.youtube.com/vi/60tSbJWJCr0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=60tSbJWJCr0",
    "supportsShuffle": false,
    "durationSeconds": 260
  },
  {
    "id": "hit-song-27",
    "section": "hits",
    "title": "Jago Uma",
    "bengaliTitle": "Jago Uma",
    "artist": "Rupankar Bagchi (Uma)",
    "bengaliArtist": "Rupankar Bagchi (Uma)",
    "type": "video",
    "youtubeId": "AoHSQ0e89sw",
    "thumbnailUrl": "https://img.youtube.com/vi/AoHSQ0e89sw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=AoHSQ0e89sw",
    "supportsShuffle": false,
    "durationSeconds": 284
  },
  {
    "id": "hit-song-28",
    "section": "hits",
    "title": "Aigiri Nandini Rock Version",
    "bengaliTitle": "Aigiri Nandini Rock Version",
    "artist": "Sowrabha",
    "bengaliArtist": "Sowrabha",
    "type": "video",
    "youtubeId": "EbcdDXEPukk",
    "thumbnailUrl": "https://img.youtube.com/vi/EbcdDXEPukk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=EbcdDXEPukk",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-29",
    "section": "hits",
    "title": "Ailo Uma Barite",
    "bengaliTitle": "Ailo Uma Barite",
    "artist": "Antara Nandy, Monami Ghosh — duplicate of #12",
    "bengaliArtist": "Antara Nandy, Monami Ghosh — duplicate of #12",
    "type": "video",
    "youtubeId": "0xDe5O7kAC0",
    "thumbnailUrl": "https://img.youtube.com/vi/0xDe5O7kAC0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=0xDe5O7kAC0",
    "supportsShuffle": false,
    "durationSeconds": 238
  },
  {
    "id": "hit-song-30",
    "section": "hits",
    "title": "Aaj Baaje",
    "bengaliTitle": "Aaj Baaje",
    "artist": "Somchanda Bhattacharya (Durga Sohay)",
    "bengaliArtist": "Somchanda Bhattacharya (Durga Sohay)",
    "type": "video",
    "youtubeId": "JrcqCpFjE7Q",
    "thumbnailUrl": "https://img.youtube.com/vi/JrcqCpFjE7Q/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=JrcqCpFjE7Q",
    "supportsShuffle": false,
    "durationSeconds": 255
  },
  {
    "id": "hit-song-31",
    "section": "hits",
    "title": "Yoddhar Saathe Ebar Pujo Katan",
    "bengaliTitle": "Yoddhar Saathe Ebar Pujo Katan",
    "artist": "Nakash Aziz",
    "bengaliArtist": "Nakash Aziz",
    "type": "video",
    "youtubeId": "tP6MIon3S5c",
    "thumbnailUrl": "https://img.youtube.com/vi/tP6MIon3S5c/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=tP6MIon3S5c",
    "supportsShuffle": false,
    "durationSeconds": 215
  },
  {
    "id": "hit-song-32",
    "section": "hits",
    "title": "Pujo Pujo Gondho",
    "bengaliTitle": "Pujo Pujo Gondho",
    "artist": "Anupam Roy",
    "bengaliArtist": "Anupam Roy",
    "type": "video",
    "youtubeId": "9fG229zIL_0",
    "thumbnailUrl": "https://img.youtube.com/vi/9fG229zIL_0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=9fG229zIL_0",
    "supportsShuffle": false,
    "durationSeconds": 248
  },
  {
    "id": "hit-song-33",
    "section": "hits",
    "title": "Pujor Dhaak Theme",
    "bengaliTitle": "Pujor Dhaak Theme",
    "artist": "Bibhabendu Bhattacharya",
    "bengaliArtist": "Bibhabendu Bhattacharya",
    "type": "video",
    "youtubeId": "uVTuUieyO7o",
    "thumbnailUrl": "https://img.youtube.com/vi/uVTuUieyO7o/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=uVTuUieyO7o",
    "supportsShuffle": false,
    "durationSeconds": 272
  },
  {
    "id": "hit-song-34",
    "section": "hits",
    "title": "Jaago Uma",
    "bengaliTitle": "Jaago Uma",
    "artist": "Anupam Roy, Rupankar Bagchi (Uma) — same song as #27",
    "bengaliArtist": "Anupam Roy, Rupankar Bagchi (Uma) — same song as #27",
    "type": "video",
    "youtubeId": "AoHSQ0e89sw",
    "thumbnailUrl": "https://img.youtube.com/vi/AoHSQ0e89sw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=AoHSQ0e89sw",
    "supportsShuffle": false,
    "durationSeconds": 198
  },
  {
    "id": "hit-song-36",
    "section": "hits",
    "title": "Aamaar Dugga",
    "bengaliTitle": "Aamaar Dugga",
    "artist": "Monali Thakur, Anindya Chattopadhyay — duplicate of #6",
    "bengaliArtist": "Monali Thakur, Anindya Chattopadhyay — duplicate of #6",
    "type": "video",
    "youtubeId": "4h5DXcN6cd4",
    "thumbnailUrl": "https://img.youtube.com/vi/4h5DXcN6cd4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=4h5DXcN6cd4",
    "supportsShuffle": false,
    "durationSeconds": 225
  },
  {
    "id": "hit-song-37",
    "section": "hits",
    "title": "Gouri Elo",
    "bengaliTitle": "Gouri Elo",
    "artist": "Dohar, Tirtha Bhattacharya (Raktabeej)",
    "bengaliArtist": "Dohar, Tirtha Bhattacharya (Raktabeej)",
    "type": "video",
    "youtubeId": "asdoVzpUFsE",
    "thumbnailUrl": "https://img.youtube.com/vi/asdoVzpUFsE/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=asdoVzpUFsE",
    "supportsShuffle": false,
    "durationSeconds": 260
  },
  {
    "id": "hit-song-38",
    "section": "hits",
    "title": "Aham Rudre",
    "bengaliTitle": "Aham Rudre",
    "artist": "Sourendro-Soumyojit Academy of Music",
    "bengaliArtist": "Sourendro-Soumyojit Academy of Music",
    "type": "video",
    "youtubeId": "zZ4dYYcPxUY",
    "thumbnailUrl": "https://img.youtube.com/vi/zZ4dYYcPxUY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=zZ4dYYcPxUY",
    "supportsShuffle": false,
    "durationSeconds": 284
  },
  {
    "id": "hit-song-39",
    "section": "hits",
    "title": "Elo Re Pujo Elo",
    "bengaliTitle": "Elo Re Pujo Elo",
    "artist": "Dabbu, Nakash Aziz, Senjuti Das",
    "bengaliArtist": "Dabbu, Nakash Aziz, Senjuti Das",
    "type": "video",
    "youtubeId": "UElpQ1D3CkA",
    "thumbnailUrl": "https://img.youtube.com/vi/UElpQ1D3CkA/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=UElpQ1D3CkA",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-40",
    "section": "hits",
    "title": "Chaarpashe Aalo Hok",
    "bengaliTitle": "Chaarpashe Aalo Hok",
    "artist": "Ajoy Chakrabarty, Kaushiki Chakraborty",
    "bengaliArtist": "Ajoy Chakrabarty, Kaushiki Chakraborty",
    "type": "video",
    "youtubeId": "mDEzESGA0h8",
    "thumbnailUrl": "https://img.youtube.com/vi/mDEzESGA0h8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=mDEzESGA0h8",
    "supportsShuffle": false,
    "durationSeconds": 238
  },
  {
    "id": "hit-song-41",
    "section": "hits",
    "title": "O Thakur",
    "bengaliTitle": "O Thakur",
    "artist": "Upal Sengupta, Prosmita Pal (Belaseshe)",
    "bengaliArtist": "Upal Sengupta, Prosmita Pal (Belaseshe)",
    "type": "video",
    "youtubeId": "7GYJcXSLwYo",
    "thumbnailUrl": "https://img.youtube.com/vi/7GYJcXSLwYo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=7GYJcXSLwYo",
    "supportsShuffle": false,
    "durationSeconds": 255
  },
  {
    "id": "hit-song-42",
    "section": "hits",
    "title": "Shubho Shubho",
    "bengaliTitle": "Shubho Shubho",
    "artist": "Altamash Faridi (Mrs. Chatterjee Vs Norway)",
    "bengaliArtist": "Altamash Faridi (Mrs. Chatterjee Vs Norway)",
    "type": "video",
    "youtubeId": "4ZWQYdzS_WY",
    "thumbnailUrl": "https://img.youtube.com/vi/4ZWQYdzS_WY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=4ZWQYdzS_WY",
    "supportsShuffle": false,
    "durationSeconds": 215
  },
  {
    "id": "hit-song-43",
    "section": "hits",
    "title": "He Maa Durga Maa",
    "bengaliTitle": "He Maa Durga Maa",
    "artist": "Aseema Panda",
    "bengaliArtist": "Aseema Panda",
    "type": "video",
    "youtubeId": "YnU9c1aj5hY",
    "thumbnailUrl": "https://img.youtube.com/vi/YnU9c1aj5hY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=YnU9c1aj5hY",
    "supportsShuffle": false,
    "durationSeconds": 248
  },
  {
    "id": "hit-song-44",
    "section": "hits",
    "title": "Durga Maa Eseche",
    "bengaliTitle": "Durga Maa Eseche",
    "artist": "Akassh",
    "bengaliArtist": "Akassh",
    "type": "video",
    "youtubeId": "l6UHhF3a0Qg",
    "thumbnailUrl": "https://img.youtube.com/vi/l6UHhF3a0Qg/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=l6UHhF3a0Qg",
    "supportsShuffle": false,
    "durationSeconds": 272
  },
  {
    "id": "hit-song-45",
    "section": "hits",
    "title": "Eseche Maa Durga Maa DJ Remix",
    "bengaliTitle": "Eseche Maa Durga Maa DJ Remix",
    "artist": "Keshab Dey, Ankita Bhattacharyya",
    "bengaliArtist": "Keshab Dey, Ankita Bhattacharyya",
    "type": "video",
    "youtubeId": "jyXKjDOANq0",
    "thumbnailUrl": "https://img.youtube.com/vi/jyXKjDOANq0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=jyXKjDOANq0",
    "supportsShuffle": false,
    "durationSeconds": 198
  },
  {
    "id": "hit-song-46",
    "section": "hits",
    "title": "Kolki",
    "bengaliTitle": "Kolki",
    "artist": "Monami Ghosh, Prativa Dutta, Rathijit Bhattacharjee",
    "bengaliArtist": "Monami Ghosh, Prativa Dutta, Rathijit Bhattacharjee",
    "type": "video",
    "youtubeId": "R4eFnxOibPs",
    "thumbnailUrl": "https://img.youtube.com/vi/R4eFnxOibPs/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=R4eFnxOibPs",
    "supportsShuffle": false,
    "durationSeconds": 225
  },
  {
    "id": "hit-song-47",
    "section": "hits",
    "title": "Dugga Ma Asche",
    "bengaliTitle": "Dugga Ma Asche",
    "artist": "Infra",
    "bengaliArtist": "Infra",
    "type": "video",
    "youtubeId": "FpM4yZfktnM",
    "thumbnailUrl": "https://img.youtube.com/vi/FpM4yZfktnM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=FpM4yZfktnM",
    "supportsShuffle": false,
    "durationSeconds": 260
  },
  {
    "id": "hit-song-48",
    "section": "hits",
    "title": "Debi Sajer Gaan",
    "bengaliTitle": "Debi Sajer Gaan",
    "artist": "Rupak Tiary, Pragya Dutta",
    "bengaliArtist": "Rupak Tiary, Pragya Dutta",
    "type": "video",
    "youtubeId": "iBAwSUu30XQ",
    "thumbnailUrl": "https://img.youtube.com/vi/iBAwSUu30XQ/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=iBAwSUu30XQ",
    "supportsShuffle": false,
    "durationSeconds": 284
  },
  {
    "id": "hit-song-49",
    "section": "hits",
    "title": "Tomake Chai",
    "bengaliTitle": "Tomake Chai",
    "artist": "Arijit Singh, Arindom (Gangster)",
    "bengaliArtist": "Arijit Singh, Arindom (Gangster)",
    "type": "video",
    "youtubeId": "jun6WZMoNWM",
    "thumbnailUrl": "https://img.youtube.com/vi/jun6WZMoNWM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=jun6WZMoNWM",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-50",
    "section": "hits",
    "title": "Meri Maa Ke Barabar Koi Nahi",
    "bengaliTitle": "Meri Maa Ke Barabar Koi Nahi",
    "artist": "Jubin Nautiyal",
    "bengaliArtist": "Jubin Nautiyal",
    "type": "video",
    "youtubeId": "fCdS-UShx4c",
    "thumbnailUrl": "https://img.youtube.com/vi/fCdS-UShx4c/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=fCdS-UShx4c",
    "supportsShuffle": false,
    "durationSeconds": 238
  },
  {
    "id": "hit-song-51",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Monali Thakur, Guddu — duplicate of #1",
    "bengaliArtist": "Monali Thakur, Guddu — duplicate of #1",
    "type": "video",
    "youtubeId": "xlElO06nQy8",
    "thumbnailUrl": "https://img.youtube.com/vi/xlElO06nQy8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xlElO06nQy8",
    "supportsShuffle": false,
    "durationSeconds": 255
  },
  {
    "id": "hit-song-52",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu",
    "bengaliTitle": "Bajlo Tomar Aalor Benu",
    "artist": "Debolina Nandy (Retro Cool Bengali Vol 3)",
    "bengaliArtist": "Debolina Nandy (Retro Cool Bengali Vol 3)",
    "type": "video",
    "youtubeId": "6xxW--m4f6I",
    "thumbnailUrl": "https://img.youtube.com/vi/6xxW--m4f6I/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=6xxW--m4f6I",
    "supportsShuffle": false,
    "durationSeconds": 215
  },
  {
    "id": "hit-song-53",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Debolinaa Nandy (Retro Cool Bengali)",
    "bengaliArtist": "Debolinaa Nandy (Retro Cool Bengali)",
    "type": "video",
    "youtubeId": "n1LORkMSIV0",
    "thumbnailUrl": "https://img.youtube.com/vi/n1LORkMSIV0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=n1LORkMSIV0",
    "supportsShuffle": false,
    "durationSeconds": 248
  },
  {
    "id": "hit-song-54",
    "section": "hits",
    "title": "Madhukaitava Vidhwangsi",
    "bengaliTitle": "Madhukaitava Vidhwangsi",
    "artist": "Tushar Dutta, Trishit, Supratik Das, Roompa (Durga)",
    "bengaliArtist": "Tushar Dutta, Trishit, Supratik Das, Roompa (Durga)",
    "type": "video",
    "youtubeId": "_GUdZJQun2I",
    "thumbnailUrl": "https://img.youtube.com/vi/_GUdZJQun2I/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=_GUdZJQun2I",
    "supportsShuffle": false,
    "durationSeconds": 272
  },
  {
    "id": "hit-song-55",
    "section": "hits",
    "title": "Kalo Jole Kuchla Tole",
    "bengaliTitle": "Kalo Jole Kuchla Tole",
    "artist": "Iman Chakraborty",
    "bengaliArtist": "Iman Chakraborty",
    "type": "video",
    "youtubeId": "YXG0AW4eidI",
    "thumbnailUrl": "https://img.youtube.com/vi/YXG0AW4eidI/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=YXG0AW4eidI",
    "supportsShuffle": false,
    "durationSeconds": 198
  },
  {
    "id": "hit-song-56",
    "section": "hits",
    "title": "Bajlo Tomar Alor Benu",
    "bengaliTitle": "Bajlo Tomar Alor Benu",
    "artist": "Sriparna Das",
    "bengaliArtist": "Sriparna Das",
    "type": "video",
    "youtubeId": "yrly1QZ5R6w",
    "thumbnailUrl": "https://img.youtube.com/vi/yrly1QZ5R6w/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=yrly1QZ5R6w",
    "supportsShuffle": false,
    "durationSeconds": 225
  },
  {
    "id": "hit-song-57",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu",
    "bengaliTitle": "Bajlo Tomar Aalor Benu",
    "artist": "Debolina Nandy — same song as #52",
    "bengaliArtist": "Debolina Nandy — same song as #52",
    "type": "video",
    "youtubeId": "6xxW--m4f6I",
    "thumbnailUrl": "https://img.youtube.com/vi/6xxW--m4f6I/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=6xxW--m4f6I",
    "supportsShuffle": false,
    "durationSeconds": 260
  },
  {
    "id": "hit-song-58",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu With Narration",
    "bengaliTitle": "Bajlo Tomar Aalor Benu With Narration",
    "artist": "Supriti Ghosh",
    "bengaliArtist": "Supriti Ghosh",
    "type": "video",
    "youtubeId": "2Zqlb00ttCU",
    "thumbnailUrl": "https://img.youtube.com/vi/2Zqlb00ttCU/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=2Zqlb00ttCU",
    "supportsShuffle": false,
    "durationSeconds": 284
  },
  {
    "id": "hit-song-59",
    "section": "hits",
    "title": "Mahishasura Mardhini",
    "bengaliTitle": "Mahishasura Mardhini",
    "artist": "Sri Vardhini, Sharath (Shakti)",
    "bengaliArtist": "Sri Vardhini, Sharath (Shakti)",
    "type": "video",
    "youtubeId": "k5ePuH_0eI0",
    "thumbnailUrl": "https://img.youtube.com/vi/k5ePuH_0eI0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=k5ePuH_0eI0",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-60",
    "section": "hits",
    "title": "Ya Chandi",
    "bengaliTitle": "Ya Chandi",
    "artist": "Chorus (Mahishasura Mardini)",
    "bengaliArtist": "Chorus (Mahishasura Mardini)",
    "type": "video",
    "youtubeId": "9Kouo0on9fw",
    "thumbnailUrl": "https://img.youtube.com/vi/9Kouo0on9fw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=9Kouo0on9fw",
    "supportsShuffle": false,
    "durationSeconds": 238
  },
  {
    "id": "og-single",
    "section": "og",
    "title": "Durga Pujo OG Hits Collection",
    "bengaliTitle": "দুর্গাপুজো ওজি ক্লাসিক কালেকশন",
    "artist": "Classic Evergreen Pujo Gaan",
    "bengaliArtist": "চিরসবুজ মেলোডি ও পুজো সুর",
    "type": "video",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=oyBQywMMi24",
    "supportsShuffle": false,
    "durationSeconds": 2975
  },
  {
    "id": "mahalaya-original",
    "section": "mahalaya",
    "title": "Mahishasuramardini Mahalaya (Full Audio)",
    "bengaliTitle": "মহিষাসুরমর্দিনী মহালয়া (সম্পূর্ণ বীরেন্দ্রকৃষ্ণ ভদ্র)",
    "artist": "Birendra Krishna Bhadra & Pankaj Mullick",
    "bengaliArtist": "বীরেন্দ্রকৃষ্ণ ভদ্র ও পঙ্কজ মল্লিক",
    "type": "video",
    "youtubeId": "A-nMCu2y_PM",
    "thumbnailUrl": "https://img.youtube.com/vi/A-nMCu2y_PM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=A-nMCu2y_PM",
    "supportsShuffle": false,
    "durationSeconds": 5400
  }
];
