export interface PujoMusicTrack {
  id: string;
  section: "hits" | "og" | "mahalaya";
  title: string;
  bengaliTitle: string;
  artist: string;
  bengaliArtist: string;
  type: "playlist" | "video" | "search";
  query?: string;
  youtubeId: string;
  thumbnailUrl: string;
  directUrl: string;
  supportsShuffle: boolean;
  durationSeconds?: number;
}

export const PUJO_MUSIC_TRACKS: PujoMusicTrack[] = [
  {
    "id": "hit-song-1",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Monali Thakur, Guddu",
    "bengaliArtist": "Monali Thakur, Guddu",
    "type": "video",
    "youtubeId": "xlElO06nQy8",
    "thumbnailUrl": "https://img.youtube.com/vi/xlElO06nQy8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xlElO06nQy8",
    "supportsShuffle": false,
    "durationSeconds": 150
  },
  {
    "id": "hit-song-2",
    "section": "hits",
    "title": "Bolo Dugga Maiki (song \"Dugga Ma\")",
    "bengaliTitle": "Bolo Dugga Maiki (song \"Dugga Ma\")",
    "artist": "Arijit Singh, Arindom",
    "bengaliArtist": "Arijit Singh, Arindom",
    "type": "video",
    "youtubeId": "sPuZ0Q3KDWo",
    "thumbnailUrl": "https://img.youtube.com/vi/sPuZ0Q3KDWo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=sPuZ0Q3KDWo",
    "supportsShuffle": false,
    "durationSeconds": 173
  },
  {
    "id": "hit-song-3",
    "section": "hits",
    "title": "Ebar Jeno Onno Rokom Pujo",
    "bengaliTitle": "Ebar Jeno Onno Rokom Pujo",
    "artist": "Nakash Aziz, Antara Mitra (Yoddha)",
    "bengaliArtist": "Nakash Aziz, Antara Mitra (Yoddha)",
    "type": "video",
    "youtubeId": "be1l6wWKUEg",
    "thumbnailUrl": "https://img.youtube.com/vi/be1l6wWKUEg/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=be1l6wWKUEg",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-4",
    "section": "hits",
    "title": "Dhak Baja Kashor Baja",
    "bengaliTitle": "Dhak Baja Kashor Baja",
    "artist": "Shreya Ghoshal",
    "bengaliArtist": "Shreya Ghoshal",
    "type": "video",
    "youtubeId": "rwyqFCznhZk",
    "thumbnailUrl": "https://img.youtube.com/vi/rwyqFCznhZk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=rwyqFCznhZk",
    "supportsShuffle": false,
    "durationSeconds": 263
  },
  {
    "id": "hit-song-5",
    "section": "hits",
    "title": "Bolo Dugga Elo (song \"Dugga Dugga\")",
    "bengaliTitle": "Bolo Dugga Elo (song \"Dugga Dugga\")",
    "artist": "Sunidhi Chauhan, Kaushik-Guddu",
    "bengaliArtist": "Sunidhi Chauhan, Kaushik-Guddu",
    "type": "video",
    "youtubeId": "PiMa4BW9Vrw",
    "thumbnailUrl": "https://img.youtube.com/vi/PiMa4BW9Vrw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=PiMa4BW9Vrw",
    "supportsShuffle": false,
    "durationSeconds": 204
  },
  {
    "id": "hit-song-6",
    "section": "hits",
    "title": "Aamaar Dugga",
    "bengaliTitle": "Aamaar Dugga",
    "artist": "Monali Thakur, Anindya Chattopadhyay",
    "bengaliArtist": "Monali Thakur, Anindya Chattopadhyay",
    "type": "video",
    "youtubeId": "4h5DXcN6cd4",
    "thumbnailUrl": "https://img.youtube.com/vi/4h5DXcN6cd4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=4h5DXcN6cd4",
    "supportsShuffle": false,
    "durationSeconds": 200
  },
  {
    "id": "hit-song-7",
    "section": "hits",
    "title": "Dhaker Taley",
    "bengaliTitle": "Dhaker Taley",
    "artist": "Abhijeet Bhattacharya, Jeet Gannguli (Poran Jai Jolia Re)",
    "bengaliArtist": "Abhijeet Bhattacharya, Jeet Gannguli (Poran Jai Jolia Re)",
    "type": "video",
    "youtubeId": "hbXuXt7gkFY",
    "thumbnailUrl": "https://img.youtube.com/vi/hbXuXt7gkFY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=hbXuXt7gkFY",
    "supportsShuffle": false,
    "durationSeconds": 263
  },
  {
    "id": "hit-song-8",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Akriti Kakar, Debanjali B Joshi",
    "bengaliArtist": "Akriti Kakar, Debanjali B Joshi",
    "type": "video",
    "youtubeId": "xytF80lvSV8",
    "thumbnailUrl": "https://img.youtube.com/vi/xytF80lvSV8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xytF80lvSV8",
    "supportsShuffle": false,
    "durationSeconds": 265
  },
  {
    "id": "hit-song-9",
    "section": "hits",
    "title": "Shundori Komola",
    "bengaliTitle": "Shundori Komola",
    "artist": "Armaan Malik, Antara Mitra (Villain)",
    "bengaliArtist": "Armaan Malik, Antara Mitra (Villain)",
    "type": "video",
    "youtubeId": "gwjWIawYyNs",
    "thumbnailUrl": "https://img.youtube.com/vi/gwjWIawYyNs/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=gwjWIawYyNs",
    "supportsShuffle": false,
    "durationSeconds": 205
  },
  {
    "id": "hit-song-10",
    "section": "hits",
    "title": "Elo Je Maa",
    "bengaliTitle": "Elo Je Maa",
    "artist": "Abhijeet Bhattacharya (Challenge 2)",
    "bengaliArtist": "Abhijeet Bhattacharya (Challenge 2)",
    "type": "video",
    "youtubeId": "2U416kTo0as",
    "thumbnailUrl": "https://img.youtube.com/vi/2U416kTo0as/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=2U416kTo0as",
    "supportsShuffle": false,
    "durationSeconds": 290
  },
  {
    "id": "hit-song-11",
    "section": "hits",
    "title": "O Menoka O Menoka",
    "bengaliTitle": "O Menoka O Menoka",
    "artist": "Antara Nandy, Ankita Nandy",
    "bengaliArtist": "Antara Nandy, Ankita Nandy",
    "type": "video",
    "youtubeId": "xUMhpMmwAmM",
    "thumbnailUrl": "https://img.youtube.com/vi/xUMhpMmwAmM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xUMhpMmwAmM",
    "supportsShuffle": false,
    "durationSeconds": 216
  },
  {
    "id": "hit-song-12",
    "section": "hits",
    "title": "Ailo Uma Barite",
    "bengaliTitle": "Ailo Uma Barite",
    "artist": "Antara Nandy, Monami Ghosh",
    "bengaliArtist": "Antara Nandy, Monami Ghosh",
    "type": "video",
    "youtubeId": "0xDe5O7kAC0",
    "thumbnailUrl": "https://img.youtube.com/vi/0xDe5O7kAC0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=0xDe5O7kAC0",
    "supportsShuffle": false,
    "durationSeconds": 119
  },
  {
    "id": "hit-song-13",
    "section": "hits",
    "title": "Uma Ashe Notun Saje",
    "bengaliTitle": "Uma Ashe Notun Saje",
    "artist": "Ankita Bhattacharyya",
    "bengaliArtist": "Ankita Bhattacharyya",
    "type": "video",
    "youtubeId": "hnkfDCbULxk",
    "thumbnailUrl": "https://img.youtube.com/vi/hnkfDCbULxk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=hnkfDCbULxk",
    "supportsShuffle": false,
    "durationSeconds": 207
  },
  {
    "id": "hit-song-14",
    "section": "hits",
    "title": "Abar Elo Maa",
    "bengaliTitle": "Abar Elo Maa",
    "artist": "Rahul Dutta, Ankita Bhattacharyya",
    "bengaliArtist": "Rahul Dutta, Ankita Bhattacharyya",
    "type": "video",
    "youtubeId": "FH-p9rnBbU4",
    "thumbnailUrl": "https://img.youtube.com/vi/FH-p9rnBbU4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=FH-p9rnBbU4",
    "supportsShuffle": false,
    "durationSeconds": 219
  },
  {
    "id": "hit-song-15",
    "section": "hits",
    "title": "Joy Joy Durga Ma",
    "bengaliTitle": "Joy Joy Durga Ma",
    "artist": "Agnibha Bandopadhyay",
    "bengaliArtist": "Agnibha Bandopadhyay",
    "type": "video",
    "youtubeId": "3E_qefwPA0E",
    "thumbnailUrl": "https://img.youtube.com/vi/3E_qefwPA0E/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=3E_qefwPA0E",
    "supportsShuffle": false,
    "durationSeconds": 209
  },
  {
    "id": "hit-song-16",
    "section": "hits",
    "title": "Durga Maa",
    "bengaliTitle": "Durga Maa",
    "artist": "Akassh, Haimanti",
    "bengaliArtist": "Akassh, Haimanti",
    "type": "video",
    "youtubeId": "9OkzYV4R9nc",
    "thumbnailUrl": "https://img.youtube.com/vi/9OkzYV4R9nc/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=9OkzYV4R9nc",
    "supportsShuffle": false,
    "durationSeconds": 242
  },
  {
    "id": "hit-song-17",
    "section": "hits",
    "title": "Gouri Elo Dekhe Jalo",
    "bengaliTitle": "Gouri Elo Dekhe Jalo",
    "artist": "Dohar",
    "bengaliArtist": "Dohar",
    "type": "video",
    "youtubeId": "W-YAf-bHkCw",
    "thumbnailUrl": "https://img.youtube.com/vi/W-YAf-bHkCw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=W-YAf-bHkCw",
    "supportsShuffle": false,
    "durationSeconds": 340
  },
  {
    "id": "hit-song-18",
    "section": "hits",
    "title": "Dhak Baaja Komor Nacha",
    "bengaliTitle": "Dhak Baaja Komor Nacha",
    "artist": "Jeet, Akriti Kakar, Dev Negi (Switzerland)",
    "bengaliArtist": "Jeet, Akriti Kakar, Dev Negi (Switzerland)",
    "type": "video",
    "youtubeId": "G7CdEseBpwc",
    "thumbnailUrl": "https://img.youtube.com/vi/G7CdEseBpwc/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=G7CdEseBpwc",
    "supportsShuffle": false,
    "durationSeconds": 220
  },
  {
    "id": "hit-song-19",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Asha Bhosle (Durga Bandana)",
    "bengaliArtist": "Asha Bhosle (Durga Bandana)",
    "type": "video",
    "youtubeId": "MMkXLPPSnwM",
    "thumbnailUrl": "https://img.youtube.com/vi/MMkXLPPSnwM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=MMkXLPPSnwM",
    "supportsShuffle": false,
    "durationSeconds": 311
  },
  {
    "id": "hit-song-20",
    "section": "hits",
    "title": "Rupang Dehi",
    "bengaliTitle": "Rupang Dehi",
    "artist": "Snita Pramanik Ghosh",
    "bengaliArtist": "Snita Pramanik Ghosh",
    "type": "video",
    "youtubeId": "IbDqRfeqjDo",
    "thumbnailUrl": "https://img.youtube.com/vi/IbDqRfeqjDo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=IbDqRfeqjDo",
    "supportsShuffle": false,
    "durationSeconds": 281
  },
  {
    "id": "hit-song-21",
    "section": "hits",
    "title": "Aigiri Nandini",
    "bengaliTitle": "Aigiri Nandini",
    "artist": "Rajalakshmee Sanjay",
    "bengaliArtist": "Rajalakshmee Sanjay",
    "type": "video",
    "youtubeId": "1Yycc3tejNw",
    "thumbnailUrl": "https://img.youtube.com/vi/1Yycc3tejNw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=1Yycc3tejNw",
    "supportsShuffle": false,
    "durationSeconds": 901
  },
  {
    "id": "hit-song-22",
    "section": "hits",
    "title": "Baja Sanai Aar Baja Re Dhol",
    "bengaliTitle": "Baja Sanai Aar Baja Re Dhol",
    "artist": "Abhijeet, Nilakshi Bhattacharya, Dev Sen (Deewana)",
    "bengaliArtist": "Abhijeet, Nilakshi Bhattacharya, Dev Sen (Deewana)",
    "type": "video",
    "youtubeId": "H9puHH3wlqs",
    "thumbnailUrl": "https://img.youtube.com/vi/H9puHH3wlqs/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=H9puHH3wlqs",
    "supportsShuffle": false,
    "durationSeconds": 265
  },
  {
    "id": "hit-song-23",
    "section": "hits",
    "title": "Elo Je Maa",
    "bengaliTitle": "Elo Je Maa",
    "artist": "Abhijeet Bhattacharya (Challenge 2) — duplicate of #10",
    "bengaliArtist": "Abhijeet Bhattacharya (Challenge 2) — duplicate of #10",
    "type": "video",
    "youtubeId": "2U416kTo0as",
    "thumbnailUrl": "https://img.youtube.com/vi/2U416kTo0as/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=2U416kTo0as",
    "supportsShuffle": false,
    "durationSeconds": 290
  },
  {
    "id": "hit-song-24",
    "section": "hits",
    "title": "Maa Ashchhe",
    "bengaliTitle": "Maa Ashchhe",
    "artist": "Sanjeev Tiwari",
    "bengaliArtist": "Sanjeev Tiwari",
    "type": "video",
    "youtubeId": "Icgq6OE7b30",
    "thumbnailUrl": "https://img.youtube.com/vi/Icgq6OE7b30/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Icgq6OE7b30",
    "supportsShuffle": false,
    "durationSeconds": 254
  },
  {
    "id": "hit-song-25",
    "section": "hits",
    "title": "Esho Maa Durga",
    "bengaliTitle": "Esho Maa Durga",
    "artist": "Shamik Guha Roy, Suman Mickey Chatterjee",
    "bengaliArtist": "Shamik Guha Roy, Suman Mickey Chatterjee",
    "type": "video",
    "youtubeId": "bQtuffhU6_4",
    "thumbnailUrl": "https://img.youtube.com/vi/bQtuffhU6_4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=bQtuffhU6_4",
    "supportsShuffle": false,
    "durationSeconds": 247
  },
  {
    "id": "hit-song-26",
    "section": "hits",
    "title": "Maa Go Tui",
    "bengaliTitle": "Maa Go Tui",
    "artist": "Somchanda Bhattacharya, Manomay Bhattacharyya (Durgeshgorer Guptodhon)",
    "bengaliArtist": "Somchanda Bhattacharya, Manomay Bhattacharyya (Durgeshgorer Guptodhon)",
    "type": "video",
    "youtubeId": "60tSbJWJCr0",
    "thumbnailUrl": "https://img.youtube.com/vi/60tSbJWJCr0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=60tSbJWJCr0",
    "supportsShuffle": false,
    "durationSeconds": 129
  },
  {
    "id": "hit-song-27",
    "section": "hits",
    "title": "Jago Uma",
    "bengaliTitle": "Jago Uma",
    "artist": "Rupankar Bagchi (Uma)",
    "bengaliArtist": "Rupankar Bagchi (Uma)",
    "type": "video",
    "youtubeId": "AoHSQ0e89sw",
    "thumbnailUrl": "https://img.youtube.com/vi/AoHSQ0e89sw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=AoHSQ0e89sw",
    "supportsShuffle": false,
    "durationSeconds": 186
  },
  {
    "id": "hit-song-28",
    "section": "hits",
    "title": "Aigiri Nandini Rock Version",
    "bengaliTitle": "Aigiri Nandini Rock Version",
    "artist": "Sowrabha",
    "bengaliArtist": "Sowrabha",
    "type": "video",
    "youtubeId": "EbcdDXEPukk",
    "thumbnailUrl": "https://img.youtube.com/vi/EbcdDXEPukk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=EbcdDXEPukk",
    "supportsShuffle": false,
    "durationSeconds": 296
  },
  {
    "id": "hit-song-29",
    "section": "hits",
    "title": "Ailo Uma Barite",
    "bengaliTitle": "Ailo Uma Barite",
    "artist": "Antara Nandy, Monami Ghosh — duplicate of #12",
    "bengaliArtist": "Antara Nandy, Monami Ghosh — duplicate of #12",
    "type": "video",
    "youtubeId": "0xDe5O7kAC0",
    "thumbnailUrl": "https://img.youtube.com/vi/0xDe5O7kAC0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=0xDe5O7kAC0",
    "supportsShuffle": false,
    "durationSeconds": 119
  },
  {
    "id": "hit-song-30",
    "section": "hits",
    "title": "Aaj Baaje",
    "bengaliTitle": "Aaj Baaje",
    "artist": "Somchanda Bhattacharya (Durga Sohay)",
    "bengaliArtist": "Somchanda Bhattacharya (Durga Sohay)",
    "type": "video",
    "youtubeId": "JrcqCpFjE7Q",
    "thumbnailUrl": "https://img.youtube.com/vi/JrcqCpFjE7Q/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=JrcqCpFjE7Q",
    "supportsShuffle": false,
    "durationSeconds": 217
  },
  {
    "id": "hit-song-31",
    "section": "hits",
    "title": "Yoddhar Saathe Ebar Pujo Katan",
    "bengaliTitle": "Yoddhar Saathe Ebar Pujo Katan",
    "artist": "Nakash Aziz",
    "bengaliArtist": "Nakash Aziz",
    "type": "video",
    "youtubeId": "tP6MIon3S5c",
    "thumbnailUrl": "https://img.youtube.com/vi/tP6MIon3S5c/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=tP6MIon3S5c",
    "supportsShuffle": false,
    "durationSeconds": 233
  },
  {
    "id": "hit-song-32",
    "section": "hits",
    "title": "Pujo Pujo Gondho",
    "bengaliTitle": "Pujo Pujo Gondho",
    "artist": "Anupam Roy",
    "bengaliArtist": "Anupam Roy",
    "type": "video",
    "youtubeId": "9fG229zIL_0",
    "thumbnailUrl": "https://img.youtube.com/vi/9fG229zIL_0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=9fG229zIL_0",
    "supportsShuffle": false,
    "durationSeconds": 167
  },
  {
    "id": "hit-song-33",
    "section": "hits",
    "title": "Pujor Dhaak Theme",
    "bengaliTitle": "Pujor Dhaak Theme",
    "artist": "Bibhabendu Bhattacharya",
    "bengaliArtist": "Bibhabendu Bhattacharya",
    "type": "video",
    "youtubeId": "uVTuUieyO7o",
    "thumbnailUrl": "https://img.youtube.com/vi/uVTuUieyO7o/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=uVTuUieyO7o",
    "supportsShuffle": false,
    "durationSeconds": 1005
  },
  {
    "id": "hit-song-34",
    "section": "hits",
    "title": "Jaago Uma",
    "bengaliTitle": "Jaago Uma",
    "artist": "Anupam Roy, Rupankar Bagchi (Uma) — same song as #27",
    "bengaliArtist": "Anupam Roy, Rupankar Bagchi (Uma) — same song as #27",
    "type": "video",
    "youtubeId": "AoHSQ0e89sw",
    "thumbnailUrl": "https://img.youtube.com/vi/AoHSQ0e89sw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=AoHSQ0e89sw",
    "supportsShuffle": false,
    "durationSeconds": 186
  },
  {
    "id": "hit-song-36",
    "section": "hits",
    "title": "Aamaar Dugga",
    "bengaliTitle": "Aamaar Dugga",
    "artist": "Monali Thakur, Anindya Chattopadhyay — duplicate of #6",
    "bengaliArtist": "Monali Thakur, Anindya Chattopadhyay — duplicate of #6",
    "type": "video",
    "youtubeId": "4h5DXcN6cd4",
    "thumbnailUrl": "https://img.youtube.com/vi/4h5DXcN6cd4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=4h5DXcN6cd4",
    "supportsShuffle": false,
    "durationSeconds": 200
  },
  {
    "id": "hit-song-37",
    "section": "hits",
    "title": "Gouri Elo",
    "bengaliTitle": "Gouri Elo",
    "artist": "Dohar, Tirtha Bhattacharya (Raktabeej)",
    "bengaliArtist": "Dohar, Tirtha Bhattacharya (Raktabeej)",
    "type": "video",
    "youtubeId": "asdoVzpUFsE",
    "thumbnailUrl": "https://img.youtube.com/vi/asdoVzpUFsE/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=asdoVzpUFsE",
    "supportsShuffle": false,
    "durationSeconds": 192
  },
  {
    "id": "hit-song-38",
    "section": "hits",
    "title": "Aham Rudre",
    "bengaliTitle": "Aham Rudre",
    "artist": "Sourendro-Soumyojit Academy of Music",
    "bengaliArtist": "Sourendro-Soumyojit Academy of Music",
    "type": "video",
    "youtubeId": "zZ4dYYcPxUY",
    "thumbnailUrl": "https://img.youtube.com/vi/zZ4dYYcPxUY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=zZ4dYYcPxUY",
    "supportsShuffle": false,
    "durationSeconds": 160
  },
  {
    "id": "hit-song-39",
    "section": "hits",
    "title": "Elo Re Pujo Elo",
    "bengaliTitle": "Elo Re Pujo Elo",
    "artist": "Dabbu, Nakash Aziz, Senjuti Das",
    "bengaliArtist": "Dabbu, Nakash Aziz, Senjuti Das",
    "type": "video",
    "youtubeId": "UElpQ1D3CkA",
    "thumbnailUrl": "https://img.youtube.com/vi/UElpQ1D3CkA/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=UElpQ1D3CkA",
    "supportsShuffle": false,
    "durationSeconds": 190
  },
  {
    "id": "hit-song-40",
    "section": "hits",
    "title": "Chaarpashe Aalo Hok",
    "bengaliTitle": "Chaarpashe Aalo Hok",
    "artist": "Ajoy Chakrabarty, Kaushiki Chakraborty",
    "bengaliArtist": "Ajoy Chakrabarty, Kaushiki Chakraborty",
    "type": "video",
    "youtubeId": "mDEzESGA0h8",
    "thumbnailUrl": "https://img.youtube.com/vi/mDEzESGA0h8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=mDEzESGA0h8",
    "supportsShuffle": false,
    "durationSeconds": 742
  },
  {
    "id": "hit-song-41",
    "section": "hits",
    "title": "O Thakur",
    "bengaliTitle": "O Thakur",
    "artist": "Upal Sengupta, Prosmita Pal (Belaseshe)",
    "bengaliArtist": "Upal Sengupta, Prosmita Pal (Belaseshe)",
    "type": "video",
    "youtubeId": "7GYJcXSLwYo",
    "thumbnailUrl": "https://img.youtube.com/vi/7GYJcXSLwYo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=7GYJcXSLwYo",
    "supportsShuffle": false,
    "durationSeconds": 170
  },
  {
    "id": "hit-song-42",
    "section": "hits",
    "title": "Shubho Shubho",
    "bengaliTitle": "Shubho Shubho",
    "artist": "Altamash Faridi (Mrs. Chatterjee Vs Norway)",
    "bengaliArtist": "Altamash Faridi (Mrs. Chatterjee Vs Norway)",
    "type": "video",
    "youtubeId": "4ZWQYdzS_WY",
    "thumbnailUrl": "https://img.youtube.com/vi/4ZWQYdzS_WY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=4ZWQYdzS_WY",
    "supportsShuffle": false,
    "durationSeconds": 175
  },
  {
    "id": "hit-song-43",
    "section": "hits",
    "title": "He Maa Durga Maa",
    "bengaliTitle": "He Maa Durga Maa",
    "artist": "Aseema Panda",
    "bengaliArtist": "Aseema Panda",
    "type": "video",
    "youtubeId": "YnU9c1aj5hY",
    "thumbnailUrl": "https://img.youtube.com/vi/YnU9c1aj5hY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=YnU9c1aj5hY",
    "supportsShuffle": false,
    "durationSeconds": 311
  },
  {
    "id": "hit-song-44",
    "section": "hits",
    "title": "Durga Maa Eseche",
    "bengaliTitle": "Durga Maa Eseche",
    "artist": "Akassh",
    "bengaliArtist": "Akassh",
    "type": "video",
    "youtubeId": "l6UHhF3a0Qg",
    "thumbnailUrl": "https://img.youtube.com/vi/l6UHhF3a0Qg/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=l6UHhF3a0Qg",
    "supportsShuffle": false,
    "durationSeconds": 36
  },
  {
    "id": "hit-song-45",
    "section": "hits",
    "title": "Eseche Maa Durga Maa DJ Remix",
    "bengaliTitle": "Eseche Maa Durga Maa DJ Remix",
    "artist": "Keshab Dey, Ankita Bhattacharyya",
    "bengaliArtist": "Keshab Dey, Ankita Bhattacharyya",
    "type": "video",
    "youtubeId": "jyXKjDOANq0",
    "thumbnailUrl": "https://img.youtube.com/vi/jyXKjDOANq0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=jyXKjDOANq0",
    "supportsShuffle": false,
    "durationSeconds": 164
  },
  {
    "id": "hit-song-46",
    "section": "hits",
    "title": "Kolki",
    "bengaliTitle": "Kolki",
    "artist": "Monami Ghosh, Prativa Dutta, Rathijit Bhattacharjee",
    "bengaliArtist": "Monami Ghosh, Prativa Dutta, Rathijit Bhattacharjee",
    "type": "video",
    "youtubeId": "R4eFnxOibPs",
    "thumbnailUrl": "https://img.youtube.com/vi/R4eFnxOibPs/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=R4eFnxOibPs",
    "supportsShuffle": false,
    "durationSeconds": 271
  },
  {
    "id": "hit-song-47",
    "section": "hits",
    "title": "Dugga Ma Asche",
    "bengaliTitle": "Dugga Ma Asche",
    "artist": "Infra",
    "bengaliArtist": "Infra",
    "type": "video",
    "youtubeId": "FpM4yZfktnM",
    "thumbnailUrl": "https://img.youtube.com/vi/FpM4yZfktnM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=FpM4yZfktnM",
    "supportsShuffle": false,
    "durationSeconds": 214
  },
  {
    "id": "hit-song-48",
    "section": "hits",
    "title": "Debi Sajer Gaan",
    "bengaliTitle": "Debi Sajer Gaan",
    "artist": "Rupak Tiary, Pragya Dutta",
    "bengaliArtist": "Rupak Tiary, Pragya Dutta",
    "type": "video",
    "youtubeId": "iBAwSUu30XQ",
    "thumbnailUrl": "https://img.youtube.com/vi/iBAwSUu30XQ/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=iBAwSUu30XQ",
    "supportsShuffle": false,
    "durationSeconds": 213
  },
  {
    "id": "hit-song-49",
    "section": "hits",
    "title": "Tomake Chai",
    "bengaliTitle": "Tomake Chai",
    "artist": "Arijit Singh, Arindom (Gangster)",
    "bengaliArtist": "Arijit Singh, Arindom (Gangster)",
    "type": "video",
    "youtubeId": "jun6WZMoNWM",
    "thumbnailUrl": "https://img.youtube.com/vi/jun6WZMoNWM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=jun6WZMoNWM",
    "supportsShuffle": false,
    "durationSeconds": 252
  },
  {
    "id": "hit-song-50",
    "section": "hits",
    "title": "Meri Maa Ke Barabar Koi Nahi",
    "bengaliTitle": "Meri Maa Ke Barabar Koi Nahi",
    "artist": "Jubin Nautiyal",
    "bengaliArtist": "Jubin Nautiyal",
    "type": "video",
    "youtubeId": "fCdS-UShx4c",
    "thumbnailUrl": "https://img.youtube.com/vi/fCdS-UShx4c/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=fCdS-UShx4c",
    "supportsShuffle": false,
    "durationSeconds": 328
  },
  {
    "id": "hit-song-51",
    "section": "hits",
    "title": "Dugga Elo",
    "bengaliTitle": "Dugga Elo",
    "artist": "Monali Thakur, Guddu — duplicate of #1",
    "bengaliArtist": "Monali Thakur, Guddu — duplicate of #1",
    "type": "video",
    "youtubeId": "xlElO06nQy8",
    "thumbnailUrl": "https://img.youtube.com/vi/xlElO06nQy8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=xlElO06nQy8",
    "supportsShuffle": false,
    "durationSeconds": 150
  },
  {
    "id": "hit-song-52",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu",
    "bengaliTitle": "Bajlo Tomar Aalor Benu",
    "artist": "Debolina Nandy (Retro Cool Bengali Vol 3)",
    "bengaliArtist": "Debolina Nandy (Retro Cool Bengali Vol 3)",
    "type": "video",
    "youtubeId": "6xxW--m4f6I",
    "thumbnailUrl": "https://img.youtube.com/vi/6xxW--m4f6I/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=6xxW--m4f6I",
    "supportsShuffle": false,
    "durationSeconds": 326
  },
  {
    "id": "hit-song-53",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Debolinaa Nandy (Retro Cool Bengali)",
    "bengaliArtist": "Debolinaa Nandy (Retro Cool Bengali)",
    "type": "video",
    "youtubeId": "n1LORkMSIV0",
    "thumbnailUrl": "https://img.youtube.com/vi/n1LORkMSIV0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=n1LORkMSIV0",
    "supportsShuffle": false,
    "durationSeconds": 234
  },
  {
    "id": "hit-song-54",
    "section": "hits",
    "title": "Madhukaitava Vidhwangsi",
    "bengaliTitle": "Madhukaitava Vidhwangsi",
    "artist": "Tushar Dutta, Trishit, Supratik Das, Roompa (Durga)",
    "bengaliArtist": "Tushar Dutta, Trishit, Supratik Das, Roompa (Durga)",
    "type": "video",
    "youtubeId": "_GUdZJQun2I",
    "thumbnailUrl": "https://img.youtube.com/vi/_GUdZJQun2I/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=_GUdZJQun2I",
    "supportsShuffle": false,
    "durationSeconds": 588
  },
  {
    "id": "hit-song-55",
    "section": "hits",
    "title": "Kalo Jole Kuchla Tole",
    "bengaliTitle": "Kalo Jole Kuchla Tole",
    "artist": "Iman Chakraborty",
    "bengaliArtist": "Iman Chakraborty",
    "type": "video",
    "youtubeId": "YXG0AW4eidI",
    "thumbnailUrl": "https://img.youtube.com/vi/YXG0AW4eidI/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=YXG0AW4eidI",
    "supportsShuffle": false,
    "durationSeconds": 311
  },
  {
    "id": "hit-song-56",
    "section": "hits",
    "title": "Bajlo Tomar Alor Benu",
    "bengaliTitle": "Bajlo Tomar Alor Benu",
    "artist": "Sriparna Das",
    "bengaliArtist": "Sriparna Das",
    "type": "video",
    "youtubeId": "yrly1QZ5R6w",
    "thumbnailUrl": "https://img.youtube.com/vi/yrly1QZ5R6w/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=yrly1QZ5R6w",
    "supportsShuffle": false,
    "durationSeconds": 292
  },
  {
    "id": "hit-song-57",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu",
    "bengaliTitle": "Bajlo Tomar Aalor Benu",
    "artist": "Debolina Nandy — same song as #52",
    "bengaliArtist": "Debolina Nandy — same song as #52",
    "type": "video",
    "youtubeId": "6xxW--m4f6I",
    "thumbnailUrl": "https://img.youtube.com/vi/6xxW--m4f6I/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=6xxW--m4f6I",
    "supportsShuffle": false,
    "durationSeconds": 326
  },
  {
    "id": "hit-song-58",
    "section": "hits",
    "title": "Bajlo Tomar Aalor Benu With Narration",
    "bengaliTitle": "Bajlo Tomar Aalor Benu With Narration",
    "artist": "Supriti Ghosh",
    "bengaliArtist": "Supriti Ghosh",
    "type": "video",
    "youtubeId": "2Zqlb00ttCU",
    "thumbnailUrl": "https://img.youtube.com/vi/2Zqlb00ttCU/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=2Zqlb00ttCU",
    "supportsShuffle": false,
    "durationSeconds": 287
  },
  {
    "id": "hit-song-59",
    "section": "hits",
    "title": "Mahishasura Mardhini",
    "bengaliTitle": "Mahishasura Mardhini",
    "artist": "Sri Vardhini, Sharath (Shakti)",
    "bengaliArtist": "Sri Vardhini, Sharath (Shakti)",
    "type": "video",
    "youtubeId": "k5ePuH_0eI0",
    "thumbnailUrl": "https://img.youtube.com/vi/k5ePuH_0eI0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=k5ePuH_0eI0",
    "supportsShuffle": false,
    "durationSeconds": 353
  },
  {
    "id": "hit-song-60",
    "section": "hits",
    "title": "Ya Chandi",
    "bengaliTitle": "Ya Chandi",
    "artist": "Chorus (Mahishasura Mardini)",
    "bengaliArtist": "Chorus (Mahishasura Mardini)",
    "type": "video",
    "youtubeId": "9Kouo0on9fw",
    "thumbnailUrl": "https://img.youtube.com/vi/9Kouo0on9fw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=9Kouo0on9fw",
    "supportsShuffle": false,
    "durationSeconds": 102
  },
  {
    "id": "hit-song-61",
    "section": "hits",
    "title": "Jago Tumi Jago",
    "bengaliTitle": "Jago Tumi Jago",
    "artist": "Trissha Chatterjee",
    "bengaliArtist": "Trissha Chatterjee",
    "type": "video",
    "youtubeId": "YC4ERU01ZxY",
    "thumbnailUrl": "https://img.youtube.com/vi/YC4ERU01ZxY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=YC4ERU01ZxY",
    "supportsShuffle": false,
    "durationSeconds": 148
  },
  {
    "id": "hit-song-62",
    "section": "hits",
    "title": "Borondala Saaja",
    "bengaliTitle": "Borondala Saaja",
    "artist": "Madhuraa Bhattacharya (Arundhuti)",
    "bengaliArtist": "Madhuraa Bhattacharya (Arundhuti)",
    "type": "video",
    "youtubeId": "gxSW8E3b3Kg",
    "thumbnailUrl": "https://img.youtube.com/vi/gxSW8E3b3Kg/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=gxSW8E3b3Kg",
    "supportsShuffle": false,
    "durationSeconds": 249
  },
  {
    "id": "hit-song-63",
    "section": "hits",
    "title": "Phagun Haoyay Haoyay",
    "bengaliTitle": "Phagun Haoyay Haoyay",
    "artist": "Jayati Chakraborty, Dipanwita Choudhury",
    "bengaliArtist": "Jayati Chakraborty, Dipanwita Choudhury",
    "type": "video",
    "youtubeId": "DlKr06Mi0Pk",
    "thumbnailUrl": "https://img.youtube.com/vi/DlKr06Mi0Pk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=DlKr06Mi0Pk",
    "supportsShuffle": false,
    "durationSeconds": 161
  },
  {
    "id": "hit-song-64",
    "section": "hits",
    "title": "Ogo Amar Agamani Alo",
    "bengaliTitle": "Ogo Amar Agamani Alo",
    "artist": "Sipra Basu",
    "bengaliArtist": "Sipra Basu",
    "type": "video",
    "youtubeId": "JWV1AAguMw4",
    "thumbnailUrl": "https://img.youtube.com/vi/JWV1AAguMw4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=JWV1AAguMw4",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-65",
    "section": "hits",
    "title": "Raai Jago Go",
    "bengaliTitle": "Raai Jago Go",
    "artist": "Pousali Banerjee",
    "bengaliArtist": "Pousali Banerjee",
    "type": "video",
    "youtubeId": "y-exkDdFJYk",
    "thumbnailUrl": "https://img.youtube.com/vi/y-exkDdFJYk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=y-exkDdFJYk",
    "supportsShuffle": false,
    "durationSeconds": 360
  },
  {
    "id": "hit-song-66",
    "section": "hits",
    "title": "Rupang Dehi",
    "bengaliTitle": "Rupang Dehi",
    "artist": "Snita Pramanik Ghosh — duplicate of #20",
    "bengaliArtist": "Snita Pramanik Ghosh — duplicate of #20",
    "type": "video",
    "youtubeId": "IbDqRfeqjDo",
    "thumbnailUrl": "https://img.youtube.com/vi/IbDqRfeqjDo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=IbDqRfeqjDo",
    "supportsShuffle": false,
    "durationSeconds": 281
  },
  {
    "id": "hit-song-67",
    "section": "hits",
    "title": "Ogo Amar Agomoni Alo",
    "bengaliTitle": "Ogo Amar Agomoni Alo",
    "artist": "Samadrita Ghosh",
    "bengaliArtist": "Samadrita Ghosh",
    "type": "video",
    "youtubeId": "OlSD9_7P__4",
    "thumbnailUrl": "https://img.youtube.com/vi/OlSD9_7P__4/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=OlSD9_7P__4",
    "supportsShuffle": false,
    "durationSeconds": 300
  },
  {
    "id": "hit-song-68",
    "section": "hits",
    "title": "Durge Durge Durgatinashini",
    "bengaliTitle": "Durge Durge Durgatinashini",
    "artist": "Asha Bhosle (Bou Katha Kao) — duplicate of #19",
    "bengaliArtist": "Asha Bhosle (Bou Katha Kao) — duplicate of #19",
    "type": "video",
    "youtubeId": "MMkXLPPSnwM",
    "thumbnailUrl": "https://img.youtube.com/vi/MMkXLPPSnwM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=MMkXLPPSnwM",
    "supportsShuffle": false,
    "durationSeconds": 311
  },
  {
    "id": "hit-song-69",
    "section": "hits",
    "title": "Agomonir Gaan",
    "bengaliTitle": "Agomonir Gaan",
    "artist": "Anupam Roy (Oriplast Originals)",
    "bengaliArtist": "Anupam Roy (Oriplast Originals)",
    "type": "video",
    "youtubeId": "MsqpjM09MrY",
    "thumbnailUrl": "https://img.youtube.com/vi/MsqpjM09MrY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=MsqpjM09MrY",
    "supportsShuffle": false,
    "durationSeconds": 363
  },
  {
    "id": "hit-song-70",
    "section": "hits",
    "title": "Saajan Rock the Dotara",
    "bengaliTitle": "Saajan Rock the Dotara",
    "artist": "Timir Biswas, Iman Chakraborty (Durga Sohay)",
    "bengaliArtist": "Timir Biswas, Iman Chakraborty (Durga Sohay)",
    "type": "video",
    "youtubeId": "hEQUxdK9I8E",
    "thumbnailUrl": "https://img.youtube.com/vi/hEQUxdK9I8E/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=hEQUxdK9I8E",
    "supportsShuffle": false,
    "durationSeconds": 267
  },
  {
    "id": "hit-song-71",
    "section": "hits",
    "title": "Pujar Gaan",
    "bengaliTitle": "Pujar Gaan",
    "artist": "Hooligaanism, Anirban Bhattacharya",
    "bengaliArtist": "Hooligaanism, Anirban Bhattacharya",
    "type": "video",
    "youtubeId": "cYt_pENoKvA",
    "thumbnailUrl": "https://img.youtube.com/vi/cYt_pENoKvA/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=cYt_pENoKvA",
    "supportsShuffle": false,
    "durationSeconds": 403
  },
  {
    "id": "hit-song-72",
    "section": "hits",
    "title": "Asatoma Sadgamaya",
    "bengaliTitle": "Asatoma Sadgamaya",
    "artist": "Arijit Singh (Khaad)",
    "bengaliArtist": "Arijit Singh (Khaad)",
    "type": "video",
    "youtubeId": "rS9IrdIbW2c",
    "thumbnailUrl": "https://img.youtube.com/vi/rS9IrdIbW2c/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=rS9IrdIbW2c",
    "supportsShuffle": false,
    "durationSeconds": 186
  },
  {
    "id": "hit-song-73",
    "section": "hits",
    "title": "Gouri Elo",
    "bengaliTitle": "Gouri Elo",
    "artist": "Aritra Dasgupta",
    "bengaliArtist": "Aritra Dasgupta",
    "type": "video",
    "youtubeId": "Q2_0ed23IwU",
    "thumbnailUrl": "https://img.youtube.com/vi/Q2_0ed23IwU/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Q2_0ed23IwU",
    "supportsShuffle": false,
    "durationSeconds": 333
  },
  {
    "id": "hit-song-74",
    "section": "hits",
    "title": "Doob De Re Mon",
    "bengaliTitle": "Doob De Re Mon",
    "artist": "Nirmalya Roy (Durgeshgorer Guptodhon)",
    "bengaliArtist": "Nirmalya Roy (Durgeshgorer Guptodhon)",
    "type": "video",
    "youtubeId": "4nC72K3Eihc",
    "thumbnailUrl": "https://img.youtube.com/vi/4nC72K3Eihc/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=4nC72K3Eihc",
    "supportsShuffle": false,
    "durationSeconds": 154
  },
  {
    "id": "hit-song-75",
    "section": "hits",
    "title": "Apur Paayer Chhaap",
    "bengaliTitle": "Apur Paayer Chhaap",
    "artist": "Arijit Singh (Apur Panchali)",
    "bengaliArtist": "Arijit Singh (Apur Panchali)",
    "type": "video",
    "youtubeId": "Rm0lQRu5hxY",
    "thumbnailUrl": "https://img.youtube.com/vi/Rm0lQRu5hxY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Rm0lQRu5hxY",
    "supportsShuffle": false,
    "durationSeconds": 226
  },
  {
    "id": "hit-song-76",
    "section": "hits",
    "title": "Esho Hey",
    "bengaliTitle": "Esho Hey",
    "artist": "Shreya Ghoshal, Ishan Mitra (Ek Je Chhilo Raja)",
    "bengaliArtist": "Shreya Ghoshal, Ishan Mitra (Ek Je Chhilo Raja)",
    "type": "video",
    "youtubeId": "zVSihjSChtw",
    "thumbnailUrl": "https://img.youtube.com/vi/zVSihjSChtw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=zVSihjSChtw",
    "supportsShuffle": false,
    "durationSeconds": 218
  },
  {
    "id": "hit-song-77",
    "section": "hits",
    "title": "Laage Ura Dhura",
    "bengaliTitle": "Laage Ura Dhura",
    "artist": "Pritom Hasan, Debosrie Antara (Toofan)",
    "bengaliArtist": "Pritom Hasan, Debosrie Antara (Toofan)",
    "type": "video",
    "youtubeId": "f53nqIBzii8",
    "thumbnailUrl": "https://img.youtube.com/vi/f53nqIBzii8/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=f53nqIBzii8",
    "supportsShuffle": false,
    "durationSeconds": 166
  },
  {
    "id": "hit-song-78",
    "section": "hits",
    "title": "Bholey Baba",
    "bengaliTitle": "Bholey Baba",
    "artist": "Badshah, Nikhita Gandhi (Villain)",
    "bengaliArtist": "Badshah, Nikhita Gandhi (Villain)",
    "type": "video",
    "youtubeId": "PuE2JqzXz0U",
    "thumbnailUrl": "https://img.youtube.com/vi/PuE2JqzXz0U/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=PuE2JqzXz0U",
    "supportsShuffle": false,
    "durationSeconds": 237
  },
  {
    "id": "hit-song-79",
    "section": "hits",
    "title": "Dushtu Kokil",
    "bengaliTitle": "Dushtu Kokil",
    "artist": "Kona, Akassh (Toofan)",
    "bengaliArtist": "Kona, Akassh (Toofan)",
    "type": "video",
    "youtubeId": "cjv6OAHIpWw",
    "thumbnailUrl": "https://img.youtube.com/vi/cjv6OAHIpWw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=cjv6OAHIpWw",
    "supportsShuffle": false,
    "durationSeconds": 217
  },
  {
    "id": "hit-song-80",
    "section": "hits",
    "title": "Mala Re",
    "bengaliTitle": "Mala Re",
    "artist": "Jeet Gannguli (Romeo)",
    "bengaliArtist": "Jeet Gannguli (Romeo)",
    "type": "video",
    "youtubeId": "fDCTCydDvMw",
    "thumbnailUrl": "https://img.youtube.com/vi/fDCTCydDvMw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=fDCTCydDvMw",
    "supportsShuffle": false,
    "durationSeconds": 279
  },
  {
    "id": "hit-song-81",
    "section": "hits",
    "title": "Koka Kola",
    "bengaliTitle": "Koka Kola",
    "artist": "Samidh Mukherjee, Kalpona Patoary",
    "bengaliArtist": "Samidh Mukherjee, Kalpona Patoary",
    "type": "video",
    "youtubeId": "RPftQkDdyPY",
    "thumbnailUrl": "https://img.youtube.com/vi/RPftQkDdyPY/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=RPftQkDdyPY",
    "supportsShuffle": false,
    "durationSeconds": 314
  },
  {
    "id": "hit-song-82",
    "section": "hits",
    "title": "Michhrir Dana",
    "bengaliTitle": "Michhrir Dana",
    "artist": "Shreya Ghoshal, Jeet Gannguli (Bibaho Obhijaan)",
    "bengaliArtist": "Shreya Ghoshal, Jeet Gannguli (Bibaho Obhijaan)",
    "type": "video",
    "youtubeId": "eXdo5lOOmuM",
    "thumbnailUrl": "https://img.youtube.com/vi/eXdo5lOOmuM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=eXdo5lOOmuM",
    "supportsShuffle": false,
    "durationSeconds": 214
  },
  {
    "id": "hit-song-83",
    "section": "hits",
    "title": "Desi Chhori",
    "bengaliTitle": "Desi Chhori",
    "artist": "Satrujit Sen, Neha Kakkar (Yoddha)",
    "bengaliArtist": "Satrujit Sen, Neha Kakkar (Yoddha)",
    "type": "video",
    "youtubeId": "dSvvoRvb7ng",
    "thumbnailUrl": "https://img.youtube.com/vi/dSvvoRvb7ng/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=dSvvoRvb7ng",
    "supportsShuffle": false,
    "durationSeconds": 242
  },
  {
    "id": "hit-song-84",
    "section": "hits",
    "title": "Party Shoes",
    "bengaliTitle": "Party Shoes",
    "artist": "Shadaab Hashmi, Neha Kakkar (Bindaas)",
    "bengaliArtist": "Shadaab Hashmi, Neha Kakkar (Bindaas)",
    "type": "video",
    "youtubeId": "QgHlVCbss4M",
    "thumbnailUrl": "https://img.youtube.com/vi/QgHlVCbss4M/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=QgHlVCbss4M",
    "supportsShuffle": false,
    "durationSeconds": 235
  },
  {
    "id": "hit-song-85",
    "section": "hits",
    "title": "Bujhina Toh Tai",
    "bengaliTitle": "Bujhina Toh Tai",
    "artist": "Nusraat Faria, Mumzy Stranger",
    "bengaliArtist": "Nusraat Faria, Mumzy Stranger",
    "type": "video",
    "youtubeId": "DoKbuK_llzI",
    "thumbnailUrl": "https://img.youtube.com/vi/DoKbuK_llzI/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=DoKbuK_llzI",
    "supportsShuffle": false,
    "durationSeconds": 201
  },
  {
    "id": "hit-song-86",
    "section": "hits",
    "title": "Lady Killer Romeo",
    "bengaliTitle": "Lady Killer Romeo",
    "artist": "Jeet Gannguli (Romeo)",
    "bengaliArtist": "Jeet Gannguli (Romeo)",
    "type": "video",
    "youtubeId": "K3xfnBCDBtA",
    "thumbnailUrl": "https://img.youtube.com/vi/K3xfnBCDBtA/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=K3xfnBCDBtA",
    "supportsShuffle": false,
    "durationSeconds": 239
  },
  {
    "id": "hit-song-87",
    "section": "hits",
    "title": "Police Chorer Preme Porechhe",
    "bengaliTitle": "Police Chorer Preme Porechhe",
    "artist": "Jeet Gannguli, Abhijeet, Akriti Kakar (Challenge 2)",
    "bengaliArtist": "Jeet Gannguli, Abhijeet, Akriti Kakar (Challenge 2)",
    "type": "video",
    "youtubeId": "sUADP6LbcAA",
    "thumbnailUrl": "https://img.youtube.com/vi/sUADP6LbcAA/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=sUADP6LbcAA",
    "supportsShuffle": false,
    "durationSeconds": 248
  },
  {
    "id": "hit-song-88",
    "section": "hits",
    "title": "Baundule Ghuri",
    "bengaliTitle": "Baundule Ghuri",
    "artist": "Anupam Roy, Arijit Singh, Shreya Ghoshal (Dawshom Awbotaar)",
    "bengaliArtist": "Anupam Roy, Arijit Singh, Shreya Ghoshal (Dawshom Awbotaar)",
    "type": "video",
    "youtubeId": "vUgO-YkQZDs",
    "thumbnailUrl": "https://img.youtube.com/vi/vUgO-YkQZDs/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=vUgO-YkQZDs",
    "supportsShuffle": false,
    "durationSeconds": 226
  },
  {
    "id": "hit-song-89",
    "section": "hits",
    "title": "Tumi Jantei Paro Naa",
    "bengaliTitle": "Tumi Jantei Paro Naa",
    "artist": "Mahtim Shakib (Cheeni 2)",
    "bengaliArtist": "Mahtim Shakib (Cheeni 2)",
    "type": "video",
    "youtubeId": "zfgF1EYV-Zk",
    "thumbnailUrl": "https://img.youtube.com/vi/zfgF1EYV-Zk/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=zfgF1EYV-Zk",
    "supportsShuffle": false,
    "durationSeconds": 107
  },
  {
    "id": "hit-song-90",
    "section": "hits",
    "title": "Taakey Olpo Kachhe Dakchhi",
    "bengaliTitle": "Taakey Olpo Kachhe Dakchhi",
    "artist": "Mahtim Shakib (Prem Tame)",
    "bengaliArtist": "Mahtim Shakib (Prem Tame)",
    "type": "video",
    "youtubeId": "Nly8TUAGyYI",
    "thumbnailUrl": "https://img.youtube.com/vi/Nly8TUAGyYI/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Nly8TUAGyYI",
    "supportsShuffle": false,
    "durationSeconds": 198
  },
  {
    "id": "hit-song-91",
    "section": "hits",
    "title": "Egiye De",
    "bengaliTitle": "Egiye De",
    "artist": "Arijit Singh, Madhubanti Bagchi (Shudhu Tomari Jonyo)",
    "bengaliArtist": "Arijit Singh, Madhubanti Bagchi (Shudhu Tomari Jonyo)",
    "type": "video",
    "youtubeId": "lgvtusNiHQo",
    "thumbnailUrl": "https://img.youtube.com/vi/lgvtusNiHQo/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=lgvtusNiHQo",
    "supportsShuffle": false,
    "durationSeconds": 261
  },
  {
    "id": "hit-song-92",
    "section": "hits",
    "title": "Shudhu Tomari Jonyo Theme",
    "bengaliTitle": "Shudhu Tomari Jonyo Theme",
    "artist": "Arijit Singh, Shreya Ghoshal",
    "bengaliArtist": "Arijit Singh, Shreya Ghoshal",
    "type": "video",
    "youtubeId": "No6v2M3eIGM",
    "thumbnailUrl": "https://img.youtube.com/vi/No6v2M3eIGM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=No6v2M3eIGM",
    "supportsShuffle": false,
    "durationSeconds": 210
  },
  {
    "id": "hit-song-93",
    "section": "hits",
    "title": "Amake Nao",
    "bengaliTitle": "Amake Nao",
    "artist": "Debayan Banerjee (Srikanto)",
    "bengaliArtist": "Debayan Banerjee (Srikanto)",
    "type": "video",
    "youtubeId": "iT4Lo-xkWao",
    "thumbnailUrl": "https://img.youtube.com/vi/iT4Lo-xkWao/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=iT4Lo-xkWao",
    "supportsShuffle": false,
    "durationSeconds": 178
  },
  {
    "id": "hit-song-94",
    "section": "hits",
    "title": "Sajani",
    "bengaliTitle": "Sajani",
    "artist": "Nilayan Chatterjee (Dilkhush)",
    "bengaliArtist": "Nilayan Chatterjee (Dilkhush)",
    "type": "video",
    "youtubeId": "MGg-RgPIzJ0",
    "thumbnailUrl": "https://img.youtube.com/vi/MGg-RgPIzJ0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=MGg-RgPIzJ0",
    "supportsShuffle": false,
    "durationSeconds": 175
  },
  {
    "id": "hit-song-95",
    "section": "hits",
    "title": "Pheshey Jaai",
    "bengaliTitle": "Pheshey Jaai",
    "artist": "Habib Wahid, Shithi Saha, Arafat Mohsin (Toofan)",
    "bengaliArtist": "Habib Wahid, Shithi Saha, Arafat Mohsin (Toofan)",
    "type": "video",
    "youtubeId": "Nhynh22zpBI",
    "thumbnailUrl": "https://img.youtube.com/vi/Nhynh22zpBI/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Nhynh22zpBI",
    "supportsShuffle": false,
    "durationSeconds": 143
  },
  {
    "id": "hit-song-96",
    "section": "hits",
    "title": "Ure Geche",
    "bengaliTitle": "Ure Geche",
    "artist": "Ash King, Monali Thakur (Parbona Ami Charte Toke)",
    "bengaliArtist": "Ash King, Monali Thakur (Parbona Ami Charte Toke)",
    "type": "video",
    "youtubeId": "Gk8jfily7-M",
    "thumbnailUrl": "https://img.youtube.com/vi/Gk8jfily7-M/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Gk8jfily7-M",
    "supportsShuffle": false,
    "durationSeconds": 224
  },
  {
    "id": "hit-song-97",
    "section": "hits",
    "title": "Aashona",
    "bengaliTitle": "Aashona",
    "artist": "Arijit Singh, Prashmita Paul (Borbaad)",
    "bengaliArtist": "Arijit Singh, Prashmita Paul (Borbaad)",
    "type": "video",
    "youtubeId": "Tt-mCnzPK-o",
    "thumbnailUrl": "https://img.youtube.com/vi/Tt-mCnzPK-o/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=Tt-mCnzPK-o",
    "supportsShuffle": false,
    "durationSeconds": 235
  },
  {
    "id": "hit-song-98",
    "section": "hits",
    "title": "Era Sukher Laagi",
    "bengaliTitle": "Era Sukher Laagi",
    "artist": "Chorus, Debojyoti Mishra (Chokher Bali)",
    "bengaliArtist": "Chorus, Debojyoti Mishra (Chokher Bali)",
    "type": "video",
    "youtubeId": "iZxoFZUE6S0",
    "thumbnailUrl": "https://img.youtube.com/vi/iZxoFZUE6S0/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=iZxoFZUE6S0",
    "supportsShuffle": false,
    "durationSeconds": 179
  },
  {
    "id": "hit-song-99",
    "section": "hits",
    "title": "Tumi Aashe Paashe",
    "bengaliTitle": "Tumi Aashe Paashe",
    "artist": "Nakash Aziz, Monali Thakur (Parbona Ami Charte Toke)",
    "bengaliArtist": "Nakash Aziz, Monali Thakur (Parbona Ami Charte Toke)",
    "type": "video",
    "youtubeId": "V-FdetrFMzw",
    "thumbnailUrl": "https://img.youtube.com/vi/V-FdetrFMzw/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=V-FdetrFMzw",
    "supportsShuffle": false,
    "durationSeconds": 279
  },
  {
    "id": "hit-song-100",
    "section": "hits",
    "title": "Hey Shokha",
    "bengaliTitle": "Hey Shokha",
    "artist": "Somlata Acharyya Chowdhury (Arindom)",
    "bengaliArtist": "Somlata Acharyya Chowdhury (Arindom)",
    "type": "video",
    "youtubeId": "oCEvYVK-M9A",
    "thumbnailUrl": "https://img.youtube.com/vi/oCEvYVK-M9A/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=oCEvYVK-M9A",
    "supportsShuffle": false,
    "durationSeconds": 365
  },
  {
    "id": "hit-song-101",
    "section": "hits",
    "title": "Shaajo Shaajao",
    "bengaliTitle": "Shaajo Shaajao",
    "artist": "Sahana Bajpaie (Ballabhpurer Roopkotha)",
    "bengaliArtist": "Sahana Bajpaie (Ballabhpurer Roopkotha)",
    "type": "video",
    "youtubeId": "tLQ1pBF32dM",
    "thumbnailUrl": "https://img.youtube.com/vi/tLQ1pBF32dM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=tLQ1pBF32dM",
    "supportsShuffle": false,
    "durationSeconds": 237
  },
  {
    "id": "hit-song-102",
    "section": "hits",
    "title": "Notun Premer Gaan",
    "bengaliTitle": "Notun Premer Gaan",
    "artist": "Debraj Bhattacharya, Surangana Bandyopadhyay (Ballabhpurer Roopkotha)",
    "bengaliArtist": "Debraj Bhattacharya, Surangana Bandyopadhyay (Ballabhpurer Roopkotha)",
    "type": "video",
    "youtubeId": "PCrKhsRHjkg",
    "thumbnailUrl": "https://img.youtube.com/vi/PCrKhsRHjkg/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=PCrKhsRHjkg",
    "supportsShuffle": false,
    "durationSeconds": 237
  },
  {
    "id": "hit-song-103",
    "section": "hits",
    "title": "Tumi Emni Esho",
    "bengaliTitle": "Tumi Emni Esho",
    "artist": "Sanchita Bhowmick (Durgo Rawhoshyo)",
    "bengaliArtist": "Sanchita Bhowmick (Durgo Rawhoshyo)",
    "type": "video",
    "youtubeId": "1E_2CAz8dLM",
    "thumbnailUrl": "https://img.youtube.com/vi/1E_2CAz8dLM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=1E_2CAz8dLM",
    "supportsShuffle": false,
    "durationSeconds": 203
  },
  {
    "id": "hit-song-104",
    "section": "hits",
    "title": "Maa Go Tui",
    "bengaliTitle": "Maa Go Tui",
    "artist": "Shovan Ganguly (Durgapujor Gaan)",
    "bengaliArtist": "Shovan Ganguly (Durgapujor Gaan)",
    "type": "video",
    "youtubeId": "HUaZHssUA3A",
    "thumbnailUrl": "https://img.youtube.com/vi/HUaZHssUA3A/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=HUaZHssUA3A",
    "supportsShuffle": false,
    "durationSeconds": 145
  },
  {
    "id": "hit-song-105",
    "section": "hits",
    "title": "Khoka Babu",
    "bengaliTitle": "Khoka Babu",
    "artist": "Rishi, Samidh (Sedin Dekha Hoyechilo)",
    "bengaliArtist": "Rishi, Samidh (Sedin Dekha Hoyechilo)",
    "type": "video",
    "youtubeId": "7SuDNW0m3TU",
    "thumbnailUrl": "https://img.youtube.com/vi/7SuDNW0m3TU/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=7SuDNW0m3TU",
    "supportsShuffle": false,
    "durationSeconds": 270
  },
  {
    "id": "hit-song-106",
    "section": "hits",
    "title": "Pyaar Ka Bukhaar",
    "bengaliTitle": "Pyaar Ka Bukhaar",
    "artist": "Jeet Gannguli, Suraj Jagan (Challenge 2)",
    "bengaliArtist": "Jeet Gannguli, Suraj Jagan (Challenge 2)",
    "type": "video",
    "youtubeId": "rVZezQEAivU",
    "thumbnailUrl": "https://img.youtube.com/vi/rVZezQEAivU/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=rVZezQEAivU",
    "supportsShuffle": false,
    "durationSeconds": 212
  },
  {
    "id": "og-single",
    "section": "og",
    "title": "Durga Pujo OG Hits Collection",
    "bengaliTitle": "দুর্গাপুজো ওজি ক্লাসিক কালেকশন",
    "artist": "Classic Evergreen Pujo Gaan",
    "bengaliArtist": "চিরসবুজ মেলোডি ও পুজো সুর",
    "type": "video",
    "youtubeId": "oyBQywMMi24",
    "thumbnailUrl": "https://img.youtube.com/vi/oyBQywMMi24/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=oyBQywMMi24",
    "supportsShuffle": false,
    "durationSeconds": 2975
  },
  {
    "id": "mahalaya-original",
    "section": "mahalaya",
    "title": "Mahishasuramardini Mahalaya (Full Audio)",
    "bengaliTitle": "মহিষাসুরমর্দিনী মহালয়া (সম্পূর্ণ বীরেন্দ্রকৃষ্ণ ভদ্র)",
    "artist": "Birendra Krishna Bhadra & Pankaj Mullick",
    "bengaliArtist": "বীরেন্দ্রকৃষ্ণ ভদ্র ও পঙ্কজ মল্লিক",
    "type": "video",
    "youtubeId": "A-nMCu2y_PM",
    "thumbnailUrl": "https://img.youtube.com/vi/A-nMCu2y_PM/hqdefault.jpg",
    "directUrl": "https://www.youtube.com/watch?v=A-nMCu2y_PM",
    "supportsShuffle": false,
    "durationSeconds": 5153
  }
];
